"""Generate the checked-in decoder index from the pinned WHATWG source, offline."""
from pathlib import Path
import argparse
import hashlib

HERE = Path(__file__).resolve().parent
SOURCE_SHA256 = "341dcde7e8b984e9c7bbf5ed75c8da7c6087d47083a1a2b3ed558bfd5bef9468"


def generate():
    data = (HERE / "index-jis0208.txt").read_bytes()
    if hashlib.sha256(data).hexdigest() != SOURCE_SHA256:
        raise ValueError("WHATWG source fingerprint changed; review and pin it before generating")
    entries = {}
    for line in data.decode("utf-8").splitlines():
        if not line or line.startswith("#"):
            continue
        pointer, scalar, *_ = line.split()
        pointer, scalar = int(pointer), int(scalar, 16)
        if pointer in entries or not 0 < scalar <= 0xffff or 0xd800 <= scalar <= 0xdfff:
            raise ValueError("invalid or duplicate BMP index entry")
        entries[pointer] = scalar
    if len(entries) != 7724 or max(entries) != 11103:
        raise ValueError("unexpected JIS0208 index dimensions")
    table = [entries.get(i, 0) for i in range(max(entries) + 1)]
    lines = [
        "/* Generated by generate_jis0208.py; do not edit.",
        "   WHATWG index-jis0208.txt SHA256 " + SOURCE_SHA256,
        "   Copyright WHATWG (Apple, Google, Mozilla, Microsoft).",
        "   Incorporated source is BSD-3-Clause; see LICENSE-WHATWG.txt.",
        "   Zero means unmapped; EUDC is handled in web_encoding.c. */",
        "static const uint16_t jis0208[11104] = {",
    ]
    for i in range(0, len(table), 12):
        lines.append("    " + ", ".join(f"0x{c:04x}" for c in table[i:i + 12]) + ",")
    lines.append("};")
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    result = generate()
    target = HERE / "jis0208.inc"
    if args.check:
        if target.read_text(encoding="utf-8") != result:
            raise SystemExit("generated JIS0208 index is stale")
    else:
        target.write_text(result, encoding="utf-8", newline="\n")
