"""公式 Unicode16 DerivedBidiClass から first-strong 専用範囲を生成。"""
from pathlib import Path
import argparse, hashlib, re

parser = argparse.ArgumentParser(description='Unicode16 Bidi_Class L/R/AL からフォーム方向表を再生成')
parser.add_argument('source', type=Path, help='公式 DerivedBidiClass.txt、SHA256 固定')
parser.add_argument('--output', type=Path, default=Path(__file__).with_name('form_direction.h'))
args = parser.parse_args()
raw = args.source.read_bytes()
if hashlib.sha256(raw).hexdigest() != '71ed943a49c58568d8d92e80ecc2ba2f06e62aee9c8ebb0e6e8bd2c3ed8b180e':
    raise SystemExit('Unicode16.0.0 DerivedBidiClass SHA256 が一致しません')
text = raw.decode('utf-8')
classes = bytearray(0x110000)
names = {'Left_To_Right': 1, 'Right_To_Left': 2, 'Arabic_Letter': 2, 'L': 1, 'R': 2, 'AL': 2}

def set_range(first, last, kind):
    a, b = int(first, 16), int(last or first, 16)
    classes[a:b+1] = bytes([names.get(kind, 0)]) * (b-a+1)

for match in re.finditer(r'# @missing: ([0-9A-F]+)(?:\.\.([0-9A-F]+))?; ([A-Za-z_]+)', text):
    set_range(*match.groups())
for line in text.splitlines():
    match = re.match(r'([0-9A-F]+)(?:\.\.([0-9A-F]+))?\s*;\s*(\w+)', line)
    if match:
        set_range(*match.groups())
ranges = []
start = 0
for value in range(1, len(classes)+1):
    if value == len(classes) or classes[value] != classes[start]:
        if classes[start]:
            ranges.append((start, value-1, classes[start]))
        start = value
header = ['#pragma once\n', '/* Generated by form_direction_generate.py from Unicode 16.0.0.\n',
          ' * https://www.unicode.org/Public/16.0.0/ucd/extracted/DerivedBidiClass.txt\n',
          f' * Source SHA256: {hashlib.sha256(raw).hexdigest()}\n',
          ' * Unicode data: form_direction_license.txt (Unicode-3.0).\n',
          ' * Only Bidi_Class L/R/AL for HTML first-strong direction; no layout bidi claim. */\n',
          'static const struct { uint32_t first, last; uint8_t direction; } form_bidi_ranges[] = {\n']
for i in range(0, len(ranges), 4):
    header.append('    ' + ', '.join('{0x%x,0x%x,%d}' % entry for entry in ranges[i:i+4]) + ',\n')
header.append('};\n')
output = ''.join(header).encode('utf-8')
args.output.write_bytes(output)
print(f'方向属性 {len(ranges)}範囲、{len(output)}バイト')
