"""Generate the checked-in C string used by the freestanding browser host."""
import json
import re
import hashlib
from pathlib import Path

base = Path(__file__).resolve().parent
source = (base / "js_bootstrap.js").read_text(encoding="utf-8")
source = re.sub(r'/\* @include ([a-z_]+\.js) \*/',
                lambda m: (base / m[1]).read_text(encoding="utf-8"), source)
# Preserve the upstream module verbatim on disk. Only its export declaration
# becomes a return inside the host-private bootstrap scope, never a page module.
streams = base.parents[2] / "third_party/web_streams"
manifest = json.loads((streams / "upstream.json").read_text(encoding="utf-8"))
ponyfill = (streams / "ponyfill.mjs").read_bytes()
if hashlib.sha256(ponyfill).hexdigest() != manifest["files"]["ponyfill.mjs"]:
    raise ValueError("Streams upstream hash mismatch")
module = ponyfill.decode("utf-8")
module, count = re.subn(r'export\{([A-Za-z,]+)\};\s*$', r'return {\1};', module)
if count != 1 or source.count("/* @streams-ponyfill */") != 1:
    raise ValueError("Streams export/include contract changed")
source = source.replace("/* @streams-ponyfill */", module)
output = "/* Generated by js_embed.py from js_bootstrap.js. */\nstatic const char js_bootstrap[] =\n"
output += "\n".join(json.dumps(line, ensure_ascii=True).replace('?', r'\?')
                    for line in source.splitlines(keepends=True))
output += ";\n"
(base / "js_bootstrap.inc").write_text(output, encoding="utf-8", newline="\n")

# Scripting-disabled native forms still use the same WHATWG URL parser. Keep
# this private source separate: it must not bootstrap a window/DOM or invoke
# any host callback from the independently budgeted validation realm.
form_url = (base / "js_form_url_prelude.js").read_text(encoding="utf-8")
form_url += (base / "js_url.js").read_text(encoding="utf-8")
form_url_output = "/* Generated by js_embed.py; private native form URL realm. */\nstatic const char js_form_url[] =\n"
form_url_output += "\n".join(json.dumps(line, ensure_ascii=True).replace('?', r'\?')
                              for line in form_url.splitlines(keepends=True))
form_url_output += ";\n"
(base / "js_form_url.inc").write_text(form_url_output, encoding="utf-8", newline="\n")
