"""Generate the checked-in C string used by the freestanding browser host."""
import json
import re
from pathlib import Path

base = Path(__file__).resolve().parent
source = (base / "js_bootstrap.js").read_text(encoding="utf-8")
source = re.sub(r'/\* @include ([a-z_]+\.js) \*/',
                lambda m: (base / m[1]).read_text(encoding="utf-8"), source)
output = "/* Generated by js_embed.py from js_bootstrap.js. */\nstatic const char js_bootstrap[] =\n"
output += "\n".join(json.dumps(line, ensure_ascii=True).replace('?', r'\?')
                    for line in source.splitlines(keepends=True))
output += ";\n"
(base / "js_bootstrap.inc").write_text(output, encoding="utf-8", newline="\n")
