"""Embed private dedicated-worker bootstrap separately from DOM/window."""
import json
import re
from pathlib import Path
base = Path(__file__).resolve().parent
source = (base / 'js_worker_runtime.js').read_text(encoding='utf-8')
source = re.sub(r'/\* @include ([a-z_]+\.js) \*/',lambda m:(base / m[1]).read_text(encoding='utf-8'),source)
output = '/* Generated by js_worker_embed.py; no DOM bootstrap. */\nstatic const char js_worker_runtime[] =\n'
output += '\n'.join(json.dumps(line,ensure_ascii=True).replace('?',r'\?') for line in source.splitlines(keepends=True))+';\n'
(base / 'js_worker_runtime.inc').write_text(output,encoding='utf-8',newline='\n')
