#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>
#include "quickjs.h"
typedef union Header {max_align_t align;struct {size_t size;} data;} Header;
typedef struct Audit {size_t allocations,live;bool deny;} Audit;
static void *alloc(JSMallocState *s,size_t n){Audit *a=s->opaque;a->allocations++;if(a->deny||n>s->malloc_limit-s->malloc_size)return NULL;Header *h=malloc(sizeof(*h)+n);if(!h)return NULL;h->data.size=n;s->malloc_count++;s->malloc_size+=n;a->live+=n;return h+1;}
static void release(JSMallocState *s,void *p){if(!p)return;Header *h=(Header*)p-1;Audit *a=s->opaque;s->malloc_count--;s->malloc_size-=h->data.size;a->live-=h->data.size;free(h);}
static void *resize(JSMallocState *s,void *p,size_t n){if(!p)return alloc(s,n);if(!n){release(s,p);return NULL;}Audit *a=s->opaque;a->allocations++;if(a->deny)return NULL;Header *old=(Header*)p-1;size_t before=old->data.size;Header *h=realloc(old,sizeof(*h)+n);if(!h)return NULL;h->data.size=n;s->malloc_size=s->malloc_size-before+n;a->live=a->live-before+n;return h+1;}
static size_t usable(const void *p){return p?((const Header*)p-1)->data.size:0;}
static JSClassID tracked_class;
static unsigned finals[256];
static JSWeakRef *observed[512];
static int checks,failures;
#define CHECK(name,expr) do{checks++;if(!(expr)){printf("FAIL %s\n",name);failures++;}}while(0)
static void finalize(JSRuntime *rt,JSValue val){uintptr_t id=(uintptr_t)JS_GetOpaque(val,tracked_class);if(id&&id<256)finals[id]++;}
static JSValue tracked(JSContext *ctx,JSValueConst this_val,int argc,JSValueConst *argv){int32_t id;if(!argc||JS_ToInt32(ctx,&id,argv[0])<0)return JS_EXCEPTION;JSValue value=JS_NewObjectClass(ctx,tracked_class);if(!JS_IsException(value))JS_SetOpaque(value,(void*)(uintptr_t)id);return value;}
static JSValue observe(JSContext *ctx,JSValueConst this_val,int argc,JSValueConst *argv){int32_t id;if(argc<2||JS_ToInt32(ctx,&id,argv[0])<0)return JS_EXCEPTION;if(id<0||id>=512)return JS_ThrowRangeError(ctx,"observation");JS_FreeWeakRef(JS_GetRuntime(ctx),observed[id]);observed[id]=JS_NewWeakRef(ctx,argv[1]);return observed[id]?JS_UNDEFINED:JS_EXCEPTION;}
static bool alive(JSContext *ctx,int id){JSValue v=JS_GetWeakRefValue(ctx,observed[id]);bool yes=!JS_IsUndefined(v);JS_FreeValue(ctx,v);return yes;}
static bool eval(JSContext *ctx,const char *source){JSValue v=JS_Eval(ctx,source,strlen(source),"ephemeron-case",JS_EVAL_TYPE_GLOBAL);bool ok=!JS_IsException(v);if(!ok){JSValue e=JS_GetException(ctx);const char *m=JS_ToCString(ctx,e);printf("JS error %s\n",m?m:"unprintable");JS_FreeCString(ctx,m);JS_FreeValue(ctx,e);}JS_FreeValue(ctx,v);return ok;}
static void install(JSContext *ctx){JSValue g=JS_GetGlobalObject(ctx);JS_SetPropertyStr(ctx,g,"tracked",JS_NewCFunction(ctx,tracked,"tracked",1));JS_SetPropertyStr(ctx,g,"observe",JS_NewCFunction(ctx,observe,"observe",2));JS_FreeValue(ctx,g);}
static void gc(JSRuntime *rt,Audit *a){size_t before=a->allocations;a->deny=true;JS_RunGC(rt);a->deny=false;CHECK("GC allocates nothing",a->allocations==before);}
int main(void){
    setvbuf(stdout,NULL,_IONBF,0);
    Audit audit={0};JSMallocFunctions mf={alloc,release,resize,usable};JSRuntime *rt=JS_NewRuntime2(&mf,&audit);JSContext *ctx=JS_NewContext(rt);JS_SetGCThreshold(rt,(size_t)-1);JS_NewClassID(&tracked_class);JSClassDef def={.class_name="GCTracked",.finalizer=finalize};CHECK("tracked class",JS_NewClass(rt,tracked_class,&def)==0);install(ctx);
    CHECK("captured key setup",eval(ctx,"globalThis.wm=new WeakMap();(()=>{let k=tracked(1),v=tracked(2);v.key=k;v.call=()=>k;wm.set(k,v);observe(1,k);observe(2,v)})();"));gc(rt,&audit);CHECK("captured key not rooted by map",!alive(ctx,1)&&!alive(ctx,2)&&finals[1]==1&&finals[2]==1);
    CHECK("live key setup",eval(ctx,"globalThis.keep=tracked(3);(()=>{let v=tracked(4);v.key=keep;wm.set(keep,v);observe(3,keep);observe(4,v)})();"));gc(rt,&audit);CHECK("live key retains value",alive(ctx,3)&&alive(ctx,4)&&!finals[4]);CHECK("live value accessible",eval(ctx,"if(wm.get(keep).key!==keep)throw new Error('live value lost');keep=null;"));gc(rt,&audit);CHECK("dropping live key collects pair",!alive(ctx,3)&&!alive(ctx,4)&&finals[3]==1&&finals[4]==1);
    CHECK("independent value setup",eval(ctx,"(()=>{let k=tracked(5),v=tracked(6);v.key=k;wm.set(k,v);globalThis.keepValue=v;observe(5,k);observe(6,v)})();"));gc(rt,&audit);CHECK("external value reaches key",alive(ctx,5)&&alive(ctx,6));eval(ctx,"keepValue=null");gc(rt,&audit);CHECK("external value drop collects",!alive(ctx,5)&&!alive(ctx,6));
    CHECK("unreachable map setup",eval(ctx,"globalThis.keep=tracked(7);(()=>{let m=new WeakMap(),v=tracked(8);v.map=m;m.set(keep,v);observe(7,keep);observe(8,v);observe(9,m)})();"));gc(rt,&audit);CHECK("live key cannot root dead map",alive(ctx,7)&&!alive(ctx,8)&&!alive(ctx,9));eval(ctx,"keep=null");
    CHECK("reverse fixed point setup",eval(ctx,"globalThis.chainMaps=[];(()=>{let keys=Array.from({length:64},(_,i)=>tracked(20+i));for(let i=63;i>=0;i--)chainMaps[i]=new WeakMap();for(let i=0;i<64;i++){observe(100+i,keys[i]);chainMaps[i].set(keys[i],{next:keys[(i+1)%64]})}globalThis.anchor=keys[0]})();"));gc(rt,&audit);bool all=true;for(int i=0;i<64;i++)all&=alive(ctx,100+i);CHECK("64 reversed conditional edges reach fixed point",all);eval(ctx,"anchor=null");gc(rt,&audit);all=true;for(int i=0;i<64;i++)all&=!alive(ctx,100+i)&&finals[20+i]==1;CHECK("unrooted ephemeron cycle collected",all);
    CHECK("nested map setup",eval(ctx,"globalThis.ka=tracked(90);globalThis.kb=tracked(91);(()=>{let inner=new WeakMap(),v=tracked(92);inner.set(kb,v);wm.set(ka,inner);observe(190,inner);observe(191,v)})();"));gc(rt,&audit);CHECK("value reaches another weak map",alive(ctx,190)&&alive(ctx,191));eval(ctx,"ka=null");gc(rt,&audit);CHECK("lost map owner prunes despite live key",!alive(ctx,190)&&!alive(ctx,191));eval(ctx,"kb=null");
    CHECK("weak set setup",eval(ctx,"globalThis.ws=new WeakSet();(()=>{let k=tracked(93);k.self=k;ws.add(k);observe(193,k)})();globalThis.sk=tracked(94);ws.add(sk);observe(194,sk);"));gc(rt,&audit);CHECK("weak set does not root cycle",!alive(ctx,193));CHECK("weak set retains live membership",alive(ctx,194)&&eval(ctx,"if(!ws.has(sk))throw new Error('set membership');sk=null"));gc(rt,&audit);CHECK("weak set dead key collected",!alive(ctx,194));
    CHECK("strong map setup",eval(ctx,"globalThis.sm=new Map();globalThis.ss=new Set();(()=>{let k=tracked(95),v=tracked(96);v.key=k;sm.set(k,v);ss.add(k);observe(195,k);observe(196,v)})();"));gc(rt,&audit);CHECK("strong map and set unchanged",alive(ctx,195)&&alive(ctx,196));eval(ctx,"sm.clear();ss.clear()");gc(rt,&audit);CHECK("strong collection release unchanged",!alive(ctx,195)&&!alive(ctx,196));
    CHECK("symbol capture setup",eval(ctx,"(()=>{let k=Symbol('captured'),v=tracked(97);v.key=k;wm.set(k,v);observe(197,k);observe(198,v)})();"));gc(rt,&audit);CHECK("symbol back reference collected",!alive(ctx,197)&&!alive(ctx,198));
    CHECK("symbol shape setup",eval(ctx,"(()=>{let k=Symbol('shape'),v=tracked(98);v[k]=true;wm.set(k,v);observe(199,k);observe(200,v)})();"));gc(rt,&audit);CHECK("symbol property-name back reference collected",!alive(ctx,199)&&!alive(ctx,200));
    CHECK("live symbol setup",eval(ctx,"globalThis.sym=Symbol('live');(()=>{let v=tracked(99);v.key=sym;wm.set(sym,v);observe(201,sym);observe(202,v)})();"));gc(rt,&audit);CHECK("live symbol retains value",alive(ctx,201)&&alive(ctx,202)&&eval(ctx,"if(!wm.has(sym))throw new Error('symbol lost')"));eval(ctx,"sym=null");gc(rt,&audit);CHECK("live symbol release collects",!alive(ctx,201)&&!alive(ctx,202));
    CHECK("strong symbol shape setup",eval(ctx,"globalThis.symbolHolder={};(()=>{let k=Symbol('held-shape'),v=tracked(100);symbolHolder[k]=1;wm.set(k,v);observe(203,k);observe(204,v)})();"));gc(rt,&audit);CHECK("reachable symbol shape activates value",alive(ctx,203)&&alive(ctx,204));eval(ctx,"symbolHolder=null");gc(rt,&audit);CHECK("symbol shape drop collects",!alive(ctx,203)&&!alive(ctx,204));
    CHECK("registered symbol rejection",eval(ctx,"let refused=false;try{wm.set(Symbol.for('registered'),{})}catch(e){refused=e instanceof TypeError}if(!refused)throw new Error('registered symbol accepted');"));
    CHECK("author callback setup",eval(ctx,"globalThis.authorCalls=0;(()=>{let k=tracked(101),v=tracked(102);Object.defineProperty(v,'value',{get(){authorCalls++;return k}});wm.set(k,v);observe(205,k);observe(206,v)})();"));gc(rt,&audit);CHECK("GC invokes no author getter",!alive(ctx,205)&&!alive(ctx,206)&&eval(ctx,"if(authorCalls)throw new Error('getter ran')"));
    JSContext *other=JS_NewContext(rt);install(other);JSValue g=JS_GetGlobalObject(ctx),m=JS_GetPropertyStr(ctx,g,"wm"),og=JS_GetGlobalObject(other);JS_SetPropertyStr(other,og,"sharedMap",m);JS_FreeValue(ctx,g);JS_FreeValue(other,og);
    CHECK("cross realm setup",eval(other,"globalThis.crossKey=tracked(103);(()=>{let v=tracked(104);v.key=crossKey;sharedMap.set(crossKey,v);observe(207,crossKey);observe(208,v)})();"));gc(rt,&audit);CHECK("cross realm live key value retained",alive(ctx,207)&&alive(ctx,208));eval(other,"crossKey=null;sharedMap=null");gc(rt,&audit);CHECK("cross realm released pair collected",!alive(ctx,207)&&!alive(ctx,208));JS_FreeContext(other);
    CHECK("deleted strong iterator setup",eval(ctx,"(()=>{let k={},v={};let m=new Map([[k,v]]),it=m.entries();m.delete(k);if(!it.next().done)throw new Error('deleted iterator record')})();"));
    for(int i=0;i<512;i++){JS_FreeWeakRef(rt,observed[i]);observed[i]=NULL;}
    JS_FreeContext(ctx);JS_FreeRuntime(rt);CHECK("runtime teardown frees allocations",audit.live==0);bool once=true;for(int i=0;i<256;i++)once&=finals[i]<=1;CHECK("native finalizers never duplicated",once);printf("ephemeron-native: %d checks, %d failures\n",checks,failures);return failures?1:0;
}
