/* Real native DOM regression batch. The caller runs the complete batch once. */
globalThis.runAttributeCases=async function(){
    let checks=0;
    const equal=(a,b,label='')=>{checks++;if(!Object.is(a,b))throw new Error('属性DOM '+label+': '+String(a)+' != '+String(b));};
    const rejects=(fn,name,label='')=>{checks++;let error;try{fn();}catch(e){error=e;}if(error?.name!==name)throw new Error('属性DOM '+label+': '+error?.name+' != '+name);};
    const HTML='http://www.w3.org/1999/xhtml', SVG='http://www.w3.org/2000/svg', XLINK='http://www.w3.org/1999/xlink',
        XML='http://www.w3.org/XML/1998/namespace', XMLNS='http://www.w3.org/2000/xmlns/', NS='urn:Nocturne:Case';
    const A=Attr, M=NamedNodeMap, n=document.createElement('div'), attrs=n.attributes;
    equal(attrs,n.attributes,'SameObject');equal(attrs instanceof M,true);equal(Object.prototype.toString.call(attrs),'[object NamedNodeMap]');
    equal(attrs.length,0);equal(n.hasAttributes(),false);equal(attrs.item(0),null);equal(attrs[0],undefined);equal(attrs.getNamedItem('absent'),null);
    rejects(()=>new A(),'TypeError');rejects(()=>new M(),'TypeError');
    n.setAttribute('DATA-A','first');const a=attrs[0];
    equal(a,n.getAttributeNode('data-a'));equal(a,attrs.getNamedItem('DATA-A'));equal(attrs['data-a'],a);
    equal(a instanceof A,true);equal(a instanceof Node,true);equal(a instanceof Element,false);
    equal(Object.getPrototypeOf(a),A.prototype);equal(Object.prototype.toString.call(a),'[object Attr]');
    equal(a.nodeType,2);equal(a.ATTRIBUTE_NODE,2);equal(Node.ATTRIBUTE_NODE,2);equal(a.name,'data-a');equal(a.nodeName,'data-a');equal(a.localName,'data-a');
    equal(a.value,'first');equal(a.nodeValue,'first');equal(a.textContent,'first');equal(a.namespaceURI,null);equal(a.prefix,null);equal(a.ownerElement,n);equal(a.ownerDocument,document);equal(a.specified,true);
    equal(a.parentNode,null);equal(a.parentElement,null);equal(a.childNodes.length,0);equal(a.firstChild,null);equal(a.nextSibling,null);equal(a.isConnected,false);equal(a.getRootNode(),a);
    n.setAttribute('data-a','second');equal(attrs[0],a);equal(a.value,'second','retained identity');
    for(const setter of ['value','nodeValue','textContent']){a[setter]=setter;equal(n.getAttribute('data-a'),setter);equal(a.value,setter);}
    a.nodeValue=null;equal(a.value,'');a.textContent=null;equal(a.value,'');a.value=null;equal(a.value,'null');
    n.setAttribute('data-b','b');n.setAttribute('data-c','c');equal(attrs.length,3);equal([...attrs].map(x=>x.name).join(','),'data-a,data-b,data-c');
    equal(Object.keys(attrs).join(','),'0,1,2');equal(Object.getOwnPropertyDescriptor(attrs,'data-a').enumerable,false);
    equal(Object.getOwnPropertyDescriptor(attrs,'0').enumerable,true);equal('data-b' in attrs,true);equal('3' in attrs,false);
    n.setAttribute('length','author');equal(attrs.length,4);equal(attrs.getNamedItem('length').value,'author','prototype names do not shadow');
    const b=attrs.item(1);n.removeAttribute('data-b');equal(b.ownerElement,null);equal(b.value,'b');equal(attrs.item(1).name,'data-c');equal(attrs.length,3);
    b.value='detached';equal(n.getAttribute('data-b'),null);equal(n.setAttributeNode(b),null);equal(b.ownerElement,n);equal(n.getAttribute('data-b'),'detached');equal(attrs.item(3),b,'append order');
    equal(n.setAttributeNode(b),b,'same node returns itself');equal(n.removeAttributeNode(b),b);equal(b.ownerElement,null);
    const replacement=document.createAttribute('DATA-A');replacement.value='replacement';
    equal(n.setAttributeNode(replacement),a);equal(a.ownerElement,null);equal(a.value,'null');equal(attrs.item(0),replacement);equal(replacement.ownerElement,n);
    a.value='still detached';equal(n.getAttribute('data-a'),'replacement');
    const other=document.createElement('div');rejects(()=>other.setAttributeNode(replacement),'InUseAttributeError');rejects(()=>other.removeAttributeNode(replacement),'NotFoundError');
    rejects(()=>attrs.removeNamedItem('absent'),'NotFoundError');rejects(()=>attrs.removeNamedItemNS('urn:none','absent'),'NotFoundError');
    equal(attrs.removeNamedItem('data-a'),replacement);equal(replacement.ownerElement,null);equal(attrs.setNamedItem(replacement),null);equal(attrs.setNamedItemNS(replacement),replacement);
    const plain=document.createAttribute('MiXeD:Name');equal(plain.name,'mixed:name');equal(plain.localName,'mixed:name');equal(plain.prefix,null);equal(plain.namespaceURI,null);equal(plain.ownerElement,null);
    const x=document.createAttributeNS(NS,'P:MiXeD');equal(x.name,'P:MiXeD');equal(x.localName,'MiXeD');equal(x.prefix,'P');equal(x.namespaceURI,NS);x.value='namespaced';
    equal(n.setAttributeNodeNS(x),null);equal(n.getAttributeNS(NS,'MiXeD'),'namespaced');equal(n.getAttributeNS(NS,'mixed'),null);equal(n.getAttributeNodeNS(NS,'MiXeD'),x);
    equal(n.getAttribute('P:MiXeD'),null,'HTML qualified-name lookup lowercases only lookup');equal(n.getAttributeNames().includes('P:MiXeD'),true);equal(attrs['P:MiXeD'],undefined,'uppercase name not a supported named property');
    n.setAttributeNS(NS,'Other:MiXeD','new');equal(x.value,'new');equal(x.prefix,'P','existing prefix retained');equal(n.getAttributeNodeNS(NS,'MiXeD'),x);
    n.setAttributeNS('urn:first','p:same','1');n.setAttributeNS('urn:second','p:same','2');
    equal(n.getAttributeNames().filter(name=>name==='p:same').length,2);equal(n.getAttribute('p:same'),'1');equal(n.getAttributeNS('urn:second','same'),'2');
    n.setAttribute('p:same','qualified');equal(n.getAttributeNS('urn:first','same'),'qualified');equal(n.getAttributeNS('urn:second','same'),'2');
    n.removeAttribute('p:same');equal(n.getAttribute('p:same'),'2');n.removeAttributeNS('urn:second','same');equal(n.hasAttributeNS('urn:second','same'),false);
    equal(attrs.getNamedItemNS(NS,'MiXeD'),x);equal(attrs.removeNamedItemNS(NS,'MiXeD'),x);equal(x.ownerElement,null);
    n.setAttributeNS('', 'bare','empty-ns');equal(n.getAttributeNS(null,'bare'),'empty-ns');equal(n.getAttributeNodeNS(null,'bare').namespaceURI,null);
    n.setAttributeNS(null,'Upper','upper');equal(n.getAttributeNS(null,'Upper'),'upper');equal(n.getAttribute('Upper'),null);equal(n.getAttributeNS(null,'upper'),null);
    n.setAttributeNS(NS,'id','namespaced-id');equal(n.id,'');equal(n.getAttributeNS(NS,'id'),'namespaced-id');
    n.id='ordinary-id';equal(n.id,'ordinary-id');equal(n.getAttributeNS(NS,'id'),'namespaced-id');
    const input=document.createElement('input');input.value='current';input.setAttributeNS(null,'VALUE','upper-value');equal(input.value,'current','uppercase null-namespace VALUE is not a control attribute');
    input.setAttribute('value','ordinary-value');equal(input.getAttributeNS(null,'VALUE'),'upper-value');equal(input.getAttribute('value'),'ordinary-value');
    const holder=document.createElement('div');holder.innerHTML='<svg viewBox="0 0 10 10" xlink:href="#a" xml:lang="ja" xmlns="'+SVG+'" xmlns:xlink="'+XLINK+'"></svg>';
    const svg=holder.firstChild, view=svg.getAttributeNode('viewBox'), link=svg.getAttributeNodeNS(XLINK,'href');
    equal(svg.namespaceURI,SVG);equal(view.localName,'viewBox');equal(view.namespaceURI,null);equal(link.name,'xlink:href');equal(link.prefix,'xlink');equal(link.localName,'href');equal(link.namespaceURI,XLINK);
    const parsedHolder=document.createElement('div');parsedHolder.innerHTML='<div id="ordinary" class="ordinary"></div><math id="math" definitionURL="math-url"></math>';
    const parsedHTML=parsedHolder.firstChild, parsedMath=parsedHolder.lastChild;
    equal(parsedHTML.getAttributeNode('id').namespaceURI,null,'HTML parser context is not an attribute namespace');equal(parsedHTML.getAttributeNode('class').namespaceURI,null);equal(parsedHTML.id,'ordinary');
    equal(parsedMath.namespaceURI,'http://www.w3.org/1998/Math/MathML');equal(parsedMath.getAttributeNode('id').namespaceURI,null);equal(parsedMath.getAttributeNode('definitionURL').namespaceURI,null);equal(parsedMath.getAttributeNode('definitionURL').localName,'definitionURL');
    equal(svg.getAttributeNode('xml:lang').namespaceURI,XML);equal(svg.getAttributeNode('xmlns').namespaceURI,XMLNS);equal(svg.getAttributeNode('xmlns:xlink').namespaceURI,XMLNS);
    svg.setAttributeNS(XLINK,'xlink:href','#b');equal(svg.getAttributeNode('xlink:href'),link);equal(link.value,'#b');link.value='#c';equal(svg.getAttributeNS(XLINK,'href'),'#c');
    const clone=svg.cloneNode(true);equal(clone.isEqualNode(svg),true);equal(clone.getAttributeNodeNS(XLINK,'href')===link,false);equal(clone.getAttributeNodeNS(XLINK,'href').prefix,'xlink');equal(clone.getAttributeNS(XLINK,'href'),'#c');
    const detachedCopy=link.cloneNode(true);equal(detachedCopy.isEqualNode(link),true);equal(detachedCopy.ownerElement,null);equal(detachedCopy.ownerDocument,document);equal(detachedCopy.name,'xlink:href');
    const owner=document.implementation.createHTMLDocument('attributes');const nativeAttr=svg.getAttributeNode('viewBox');
    owner.adoptNode(svg);equal(svg.ownerDocument,owner);equal(nativeAttr.ownerDocument,owner);equal(nativeAttr.ownerElement,svg);equal(svg.getAttributeNode('viewBox'),nativeAttr);
    const imported=document.importNode(svg,true);equal(imported.ownerDocument,document);equal(imported.getAttributeNodeNS(XLINK,'href').ownerDocument,document);equal(imported.getAttributeNodeNS(XLINK,'href').namespaceURI,XLINK);
    equal(document.adoptNode(link),link);equal(link.ownerElement,null);equal(link.ownerDocument,document);equal(svg.getAttributeNodeNS(XLINK,'href'),null);
    equal(document.importNode(nativeAttr,true).ownerElement,null);equal(document.importNode(nativeAttr,true).value,'0 0 10 10');
    const observed=document.createElement('div'), observer=new MutationObserver(()=>{});observer.observe(observed,{attributes:true,attributeOldValue:true});
    observed.setAttribute('data-x','1');const watched=observed.getAttributeNode('data-x');watched.value='2';watched.nodeValue='3';watched.textContent='4';
    const watchedNew=document.createAttribute('data-x');watchedNew.value='5';observed.setAttributeNode(watchedNew);observed.setAttributeNode(watchedNew);observed.removeAttributeNode(watchedNew);
    observed.setAttributeNS(NS,'p:track','N1');observed.getAttributeNodeNS(NS,'track').value='N2';observed.removeAttributeNS(NS,'track');
    const records=observer.takeRecords();observer.disconnect();equal(records.length,9);equal(records.map(r=>r.oldValue).join('|'),'|1|2|3|4|5||N1|N2');
    equal(records.slice(0,6).every(r=>r.attributeName==='data-x' && r.attributeNamespace===null && r.target===observed),true);
    equal(records.slice(6).every(r=>r.attributeName==='track' && r.attributeNamespace===NS && r.target===observed),true);
    const filtered=new MutationObserver(()=>{});filtered.observe(observed,{attributes:true,attributeFilter:['track']});observed.setAttributeNS(NS,'p:track','NS');observed.setAttribute('track','plain');
    equal(filtered.takeRecords().length,1,'attributeFilter does not match namespaced attributes');filtered.disconnect();
    const adoptionObserver=new MutationObserver(()=>{});adoptionObserver.observe(observed,{attributes:true,attributeOldValue:true});
    const adoptedAttr=observed.getAttributeNode('track');owner.adoptNode(adoptedAttr);const removal=adoptionObserver.takeRecords();adoptionObserver.disconnect();equal(removal.length,1);equal(removal[0].oldValue,'plain');equal(adoptedAttr.ownerDocument,owner);equal(adoptedAttr.ownerElement,null);
    class AttributeBatchElement extends HTMLElement {static get observedAttributes(){return ['data-x','track'];}attributeChangedCallback(name,old,value,ns){this.calls??=[];this.calls.push([name,old,value,ns]);}}
    if(!customElements.get('attribute-batch-element'))customElements.define('attribute-batch-element',AttributeBatchElement);
    const ce=document.createElement('attribute-batch-element');ce.setAttribute('data-x','1');ce.getAttributeNode('data-x').value='2';ce.setAttributeNS(NS,'p:track','3');ce.removeAttributeNS(NS,'track');
    equal(ce.calls.length,4);equal(ce.calls[1].join('|'),'data-x|1|2|');equal(ce.calls[2][3],NS);equal(ce.calls[3][2],null);
    const late=document.createElement('attribute-late-element');late.setAttributeNS(NS,'P:track','initial');
    class LateAttributeElement extends HTMLElement {static get observedAttributes(){return ['track'];}attributeChangedCallback(name,old,value,ns){this.initial=[name,old,value,ns];}}
    if(!customElements.get('attribute-late-element'))customElements.define('attribute-late-element',LateAttributeElement);customElements.upgrade(late);
    equal(late.initial[0],'track');equal(late.initial[1],null);equal(late.initial[2],'initial');equal(late.initial[3],NS,'upgrade callbacks preserve namespace');
    const button=document.createElement('button'), onclick=document.createAttribute('onclick');onclick.value='this.__attributeClicks=(this.__attributeClicks||0)+1';button.setAttributeNode(onclick);button.dispatchEvent(new Event('click'));
    equal(button.__attributeClicks,1,'inline handler Attr insertion');onclick.value='this.__attributeClicks+=2';button.dispatchEvent(new Event('click'));equal(button.__attributeClicks,3,'inline handler Attr value update');button.removeAttributeNode(onclick);button.dispatchEvent(new Event('click'));equal(button.__attributeClicks,3,'inline handler Attr removal');
    const script=document.createElement('script'), async=document.createAttribute('async');equal(script.async,true);script.setAttributeNode(async);script.removeAttributeNode(async);equal(script.async,false,'async presence via Attr clears forced-async');
    const invalid=['','bad name','bad\nname','bad/name','bad=name','bad>name','bad\0name'];
    for(const name of invalid){rejects(()=>document.createAttribute(name),'InvalidCharacterError');rejects(()=>n.setAttribute(name,'x'),'InvalidCharacterError');}
    rejects(()=>document.createAttributeNS(null,'p:name'),'NamespaceError');rejects(()=>document.createAttributeNS('urn:wrong','xml:lang'),'NamespaceError');
    rejects(()=>document.createAttributeNS('urn:wrong','xmlns'),'NamespaceError');rejects(()=>document.createAttributeNS(XMLNS,'name'),'NamespaceError');
    rejects(()=>document.createAttributeNS(NS,':name'),'InvalidCharacterError');rejects(()=>n.setAttributeNS(NS,'p:','x'),'InvalidCharacterError');
    equal(document.createAttribute('9name').name,'9name','current relaxed attribute grammar');equal(document.createAttribute('@name').name,'@name');equal(document.createAttributeNS(NS,'p:a:b').localName,'a:b');
    rejects(()=>document.createAttribute('x'.repeat(128)),'NotSupportedError','explicit native size boundary');
    rejects(()=>{replacement.value='a\0b';},'NotSupportedError','NUL values are not silently truncated');
    rejects(()=>n.setAttributeNS('urn:a\0b','name','value'),'NotSupportedError','NUL namespace boundary');
    for(const fn of [()=>n.getAttribute(),()=>n.setAttribute('x'),()=>n.getAttributeNS(null),()=>attrs.item(),()=>attrs.setNamedItem(),()=>document.createAttributeNS(NS)])rejects(fn,'TypeError');
    for(const fn of [()=>n.setAttribute(Symbol('name'),'x'),()=>{replacement.value=Symbol('value');},()=>attrs.getNamedItemNS(Symbol('ns'),'x'),()=>attrs.item(Symbol('index'))])rejects(fn,'TypeError');
    rejects(()=>Element.prototype.getAttributeNode.call({},'x'),'TypeError');rejects(()=>M.prototype.item.call({},0),'TypeError');rejects(()=>Object.getOwnPropertyDescriptor(A.prototype,'value').get.call({}),'TypeError');
    const saved={Attr:globalThis.Attr,NamedNodeMap:globalThis.NamedNodeMap};try{globalThis.Attr=function Fake(){};globalThis.NamedNodeMap=function FakeMap(){};
        const fresh=document.createAttribute('native');equal(Object.getPrototypeOf(fresh),A.prototype);equal(document.createElement('div').attributes instanceof M,true);
        Object.defineProperty(fresh,'ownerElement',{value:other});equal(n.setAttributeNode(fresh),null,'public ownership spoof cannot retarget native Attr');equal(fresh.value,'');
    }finally{Object.assign(globalThis,saved);}
    const reflected=document.createElement('input');reflected.setAttributeNS(NS,'disabled','');reflected.setAttributeNS(NS,'checked','');reflected.setAttributeNS(NS,'value','private');
    equal(reflected.disabled,false);equal(reflected.defaultChecked,false);equal(reflected.defaultValue,'');
    reflected.disabled=true;reflected.defaultChecked=true;reflected.defaultValue='ordinary';
    equal(reflected.getAttributeNS(null,'disabled'),'');equal(reflected.getAttributeNS(null,'checked'),'');equal(reflected.getAttributeNS(null,'value'),'ordinary');equal(reflected.getAttributeNS(NS,'value'),'private');
    reflected.setAttributeNS(NS,'data-x','private');equal(reflected.dataset.x,null);reflected.dataset.x='ordinary';equal(reflected.getAttributeNS(null,'data-x'),'ordinary');equal(reflected.getAttributeNS(NS,'data-x'),'private');
    const namespaceScript=document.createElement('script');namespaceScript.setAttributeNS(NS,'async','private');namespaceScript.async=true;namespaceScript.async=false;
    equal(namespaceScript.getAttributeNS(null,'async'),null);equal(namespaceScript.getAttributeNS(NS,'async'),'private');
    const namespaceImage=document.createElement('img');namespaceImage.setAttributeNS(NS,'width','99');namespaceImage.width=23;
    equal(namespaceImage.getAttributeNS(null,'width'),'23');equal(namespaceImage.getAttributeNS(NS,'width'),'99');
    const namespaceSVG=document.createElementNS(SVG,'svg');namespaceSVG.setAttributeNS(NS,'class','private');equal(namespaceSVG.className.baseVal,'');namespaceSVG.classList.add('ordinary');equal(namespaceSVG.className.baseVal,'ordinary');equal(namespaceSVG.getAttributeNS(NS,'class'),'private');
    const namespaceHandler=document.createElement('button');namespaceHandler.setAttributeNS(NS,'onclick','throw new Error("namespace handler executed")');namespaceHandler.dispatchEvent(new Event('click'));equal(namespaceHandler.onclick,null);
    const ceAdopt=document.createElement('attribute-batch-element');ceAdopt.setAttribute('data-x','before');owner.adoptNode(ceAdopt.getAttributeNode('data-x'));equal(ceAdopt.calls.length,2);equal(ceAdopt.calls[1][2],null);
    equal(n.namespaceURI,HTML);return checks;
};
