/* Real native RGBA gradients; no mock contexts or successful GPU facades. */
(()=>{
  let count=0,failed=0;
  const assert=(name,value)=>{count++;if(!value)failed++;console.log((value?'OK gradient ':'FAIL gradient ')+name);};
  const throws=(name,fn,type)=>{let caught=false;try{fn();}catch(e){caught=e.name===type;}assert(name,caught);};
  const canvas=document.getElementById('gradient'),ctx=canvas.getContext('2d');
  const reset=()=>{ctx.reset();};
  const pixel=(x,y)=>Array.from(ctx.getImageData(x,y,1,1).data);
  const near=(p,v,tolerance=2)=>p.every((n,i)=>Math.abs(n-v[i])<=tolerance);
  const checkPixel=(name,x,y,expected,tolerance=2)=>{const actual=pixel(x,y);console.log('GRADIENT-PIXEL '+name+' '+actual+' expected '+expected);assert(name,near(actual,expected,tolerance));};
  const stops=(g,a='red',b='blue')=>{g.addColorStop(0,a);g.addColorStop(1,b);return g;};
  const linear=(...v)=>stops(ctx.createLinearGradient(...v));
  const fill=g=>{ctx.fillStyle=g;ctx.fillRect(0,0,64,64);};

  assert('public-real-gradient',typeof CanvasGradient==='function'&&typeof ctx.createRadialGradient==='function');
  throws('illegal-constructor',()=>new CanvasGradient(),'TypeError');
  throws('linear-receiver',()=>CanvasRenderingContext2D.prototype.createLinearGradient.call({},0,0,1,0),'TypeError');
  throws('radial-receiver',()=>CanvasRenderingContext2D.prototype.createRadialGradient.call({},0,0,0,1,1,2),'TypeError');
  throws('stop-receiver',()=>CanvasGradient.prototype.addColorStop.call({},0,'red'),'TypeError');
  throws('prototype-not-instance',()=>CanvasGradient.prototype.addColorStop(0,'red'),'TypeError');
  throws('linear-missing',()=>ctx.createLinearGradient(0,0,1),'TypeError');
  throws('radial-missing',()=>ctx.createRadialGradient(0,0,0,0,0),'TypeError');
  throws('linear-infinity',()=>ctx.createLinearGradient(Infinity,0,1,0),'TypeError');
  throws('radial-nan',()=>ctx.createRadialGradient(0,0,0,0,NaN,1),'TypeError');
  throws('gradient-bigint',()=>ctx.createLinearGradient(0n,0,1,0),'TypeError');
  let laterConversion=0;
  throws('gradient-restricted-conversion-order',()=>ctx.createLinearGradient(NaN,{valueOf(){laterConversion++;return 0;}},1,0),'TypeError');
  assert('gradient-later-conversion-skipped',laterConversion===0);
  throws('negative-first-radius',()=>ctx.createRadialGradient(0,0,-1,0,0,2),'IndexSizeError');
  throws('negative-last-radius',()=>ctx.createRadialGradient(0,0,1,0,0,-2),'IndexSizeError');
  const g=linear(0,0,8,0);
  assert('prototype-and-tag',g instanceof CanvasGradient&&Object.getPrototypeOf(g)===CanvasGradient.prototype&&Object.prototype.toString.call(g)==='[object CanvasGradient]');
  throws('stop-missing',()=>g.addColorStop(0),'TypeError');
  throws('stop-nan',()=>g.addColorStop(NaN,'red'),'TypeError');
  throws('stop-infinite',()=>g.addColorStop(Infinity,'red'),'TypeError');
  throws('stop-bigint',()=>g.addColorStop(0n,'red'),'TypeError');
  throws('stop-negative',()=>g.addColorStop(-0.01,'red'),'IndexSizeError');
  throws('stop-over-one',()=>g.addColorStop(1.01,'red'),'IndexSizeError');
  throws('stop-invalid-color',()=>g.addColorStop(0,'not-a-color'),'SyntaxError');
  throws('stop-malformed-color',()=>g.addColorStop(0,'rgb(1, 2, 3, 4, 5)'),'SyntaxError');
  throws('stop-css-wide-keyword',()=>g.addColorStop(0,'inherit'),'SyntaxError');
  let coerced=0;
  throws('restricted-double-before-color',()=>g.addColorStop(NaN,{toString(){coerced++;return 'red';}}),'TypeError');
  assert('nonfinite-no-color-conversion',coerced===0);
  const converted=ctx.createLinearGradient({valueOf(){coerced++;return 0;}},0,8,0);
  converted.addColorStop({valueOf(){coerced++;return 0;}},{toString(){coerced++;return 'lime';}});
  assert('single-argument-conversions',coerced===3);
  reset();fill(g);
  assert('fill-style-identity',ctx.fillStyle===g);
  checkPixel('horizontal-start',0,2,[239,0,16,255]);
  checkPixel('horizontal-middle',4,2,[112,0,143,255]);
  checkPixel('horizontal-extended-last',10,2,[0,0,255,255]);
  reset();fill(linear(0,0,0,8));checkPixel('vertical',2,4,[112,0,143,255]);
  reset();fill(linear(8,0,0,0));checkPixel('reverse-linear',4,2,[143,0,112,255]);
  reset();fill(linear(0,0,8,8));checkPixel('diagonal-projection',2,5,[128,0,128,255]);
  reset();const range=ctx.createLinearGradient(0,0,8,0);range.addColorStop(.75,'blue');range.addColorStop(.25,'red');fill(range);
  checkPixel('before-first-stop',0,0,[255,0,0,255]);checkPixel('after-last-stop',7,0,[0,0,255,255]);
  reset();const duplicate=ctx.createLinearGradient(0,0,9,0);
  for(const [n,c] of [[0,'red'],[.5,'red'],[.5,'lime'],[.5,'blue'],[1,'blue']])duplicate.addColorStop(n,c);
  fill(duplicate);checkPixel('duplicate-before',3,0,[255,0,0,255]);
  checkPixel('duplicate-order-at-stop',4,0,[0,0,255,255]);checkPixel('duplicate-after',5,0,[0,0,255,255]);
  reset();ctx.fillStyle='lime';ctx.fillRect(0,0,64,64);fill(ctx.createLinearGradient(0,0,8,0));
  checkPixel('no-stops-preserve-destination',3,3,[0,255,0,255]);
  reset();const one=ctx.createLinearGradient(0,0,8,0);one.addColorStop(.4,'#123456');fill(one);
  checkPixel('single-stop-solid',3,3,[18,52,86,255]);
  reset();fill(stops(ctx.createLinearGradient(0,0,9,0),'rgba(255,0,0,0)','blue'));
  checkPixel('unpremultiplied-rgb-alpha',4,2,[128,0,128,128]);
  reset();ctx.globalAlpha=.5;fill(g);checkPixel('global-alpha-once',4,2,[112,0,143,128]);
  reset();ctx.fillStyle='white';ctx.fillRect(0,0,64,64);ctx.globalAlpha=.5;fill(g);
  checkPixel('source-over-existing-white',4,2,[183,127,199,255]);
  reset();fill(linear(2,2,2,2));checkPixel('degenerate-linear',2,2,[0,0,0,0]);
  reset();const cc=ctx.createLinearGradient(0,0,8,0);cc.addColorStop(0,'currentColor');fill(cc);
  checkPixel('canvas-neutral-current-color',2,2,[0,0,0,255]);
  reset();ctx.fillStyle=g;ctx.strokeStyle=g;ctx.save();ctx.fillStyle='lime';ctx.strokeStyle='white';ctx.globalAlpha=.25;ctx.translate(20,20);ctx.restore();
  assert('save-restore-style-reference',ctx.fillStyle===g&&ctx.strokeStyle===g&&ctx.globalAlpha===1);
  ctx.fillRect(0,0,8,8);checkPixel('save-restore-transform',4,2,[112,0,143,255]);
  reset();const mutable=ctx.createLinearGradient(0,0,8,0);ctx.fillStyle=mutable;ctx.fillRect(0,0,8,8);
  mutable.addColorStop(0,'red');ctx.fillRect(0,0,8,8);checkPixel('stop-mutation-after-assignment',2,2,[255,0,0,255]);
  mutable.addColorStop(0,'blue');ctx.fillRect(0,0,8,8);checkPixel('stop-cache-invalidated',2,2,[0,0,255,255]);
  const second=document.createElement('canvas');second.width=8;second.height=8;const sctx=second.getContext('2d');sctx.fillStyle=g;sctx.fillRect(0,0,8,8);
  assert('gradient-other-canvas-identity',sctx.fillStyle===g);
  assert('gradient-other-canvas-pixels',near(Array.from(sctx.getImageData(4,2,1,1).data),[112,0,143,255]));

  reset();ctx.translate(10,4);fill(g);checkPixel('paint-time-translation',14,6,[112,0,143,255]);
  reset();ctx.scale(2,1);fill(g);checkPixel('nonuniform-scale-linear',8,2,[120,0,135,255]);
  reset();ctx.setTransform(1,0,1,1,4,2);fill(g);checkPixel('shear-linear',10,4,[128,0,128,255]);
  reset();ctx.setTransform(0,1,-1,0,16,0);fill(g);checkPixel('rotation-linear',14,4,[112,0,143,255]);
  reset();ctx.translate(20,20);const delayed=linear(0,0,8,0);ctx.resetTransform();fill(delayed);
  checkPixel('creation-transform-not-captured',4,2,[112,0,143,255]);
  reset();ctx.beginPath();ctx.rect(0,0,8,8);ctx.clip();fill(g);
  checkPixel('clip-inside',4,2,[112,0,143,255]);checkPixel('clip-outside',10,2,[0,0,0,0]);
  ctx.clearRect(0,0,8,8);checkPixel('clear-ignores-gradient',4,2,[0,0,0,0]);
  reset();ctx.fillStyle=g;ctx.beginPath();ctx.moveTo(0,0);ctx.lineTo(8,0);ctx.lineTo(8,8);ctx.lineTo(0,8);ctx.fill();
  checkPixel('gradient-polygon-fill',4,2,[112,0,143,255]);
  reset();ctx.strokeStyle=g;ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(0,4);ctx.lineTo(8,4);ctx.stroke();
  assert('stroke-style-identity',ctx.strokeStyle===g);checkPixel('gradient-stroke',4,4,[112,0,143,255]);
  reset();ctx.strokeStyle=g;ctx.lineWidth=2;ctx.strokeRect(0,0,8,8);checkPixel('gradient-stroke-rect',4,0,[112,0,143,255]);
  reset();ctx.fillStyle=g;ctx.fillText('MMMM',0,24);
  const text=ctx.getImageData(0,0,40,32).data;let ink=false,correct=true;
  for(let y=0;y<32;y++)for(let x=0;x<40;x++){const i=(y*40+x)*4;if(text[i+3]){ink=true;const t=Math.min(1,(x+.5)/8);if(Math.abs(text[i]-Math.round(255*(1-t)))>2||text[i+1]!==0||Math.abs(text[i+2]-Math.round(255*t))>2)correct=false;}}
  assert('gradient-native-text-coverage',ink&&correct);

  reset();const radial=stops(ctx.createRadialGradient(16,16,0,16,16,8));fill(radial);
  const t=Math.hypot(.5,.5)/8;checkPixel('radial-near-center',16,16,[Math.round(255*(1-t)),0,Math.round(255*t),255]);
  const rt=Math.hypot(4.5,.5)/8;checkPixel('radial-intermediate',20,16,[Math.round(255*(1-rt)),0,Math.round(255*rt),255]);
  checkPixel('radial-extended-last',25,16,[0,0,255,255]);
  reset();fill(stops(ctx.createRadialGradient(16.5,16.5,0,16.5,16.5,8)));
  checkPixel('collapsed-circle-center-limit',16,16,[255,0,0,255]);
  reset();fill(stops(ctx.createRadialGradient(16,16,2,16,16,8)));
  checkPixel('radial-extended-first',16,16,[255,0,0,255]);
  reset();fill(stops(ctx.createRadialGradient(16,16,8,16,16,0)));
  checkPixel('radial-decreasing-radii',20,16,[Math.round(255*rt),0,Math.round(255*(1-rt)),255]);
  reset();fill(stops(ctx.createRadialGradient(8,16,0,16,16,8)));
  checkPixel('offset-cone-positive-root',16,16,[119,0,136,255],3);
  checkPixel('offset-cone-outside-preserved',2,16,[0,0,0,0]);
  reset();fill(stops(ctx.createRadialGradient(8.5,16.5,1,16.5,16.5,9)));
  checkPixel('tangent-cone-boundary-limit',7,16,[0,0,255,255]);
  reset();fill(stops(ctx.createRadialGradient(8,16,2,16,16,2)));
  checkPixel('equal-radii-moving-centers-greatest-root',12,16,[50,0,205,255],3);
  checkPixel('equal-radii-outside-cone',12,20,[0,0,0,0]);
  reset();fill(stops(ctx.createRadialGradient(16,16,4,16,16,4)));checkPixel('identical-circles-no-paint',16,16,[0,0,0,0]);
  reset();fill(stops(ctx.createRadialGradient(8,8,0,16,16,0)));checkPixel('zero-radius-family-no-paint',12,12,[0,0,0,0]);
  reset();ctx.scale(2,1);fill(radial);
  const scaled=Math.hypot(2.25,.5)/8;checkPixel('elliptical-affine-radial',36,16,[Math.round(255*(1-scaled)),0,Math.round(255*scaled),255]);
  reset();ctx.setTransform(1,0,0,0,0,0);ctx.fillStyle=radial;ctx.beginPath();ctx.resetTransform();ctx.rect(0,0,64,64);ctx.setTransform(1,0,0,0,0,0);ctx.fill();
  checkPixel('singular-radial-transparent',16,16,[0,0,0,0]);
  reset();const fade=stops(ctx.createRadialGradient(32,32,0,32,32,32),'rgba(0,0,0,1)','rgba(0,0,0,0)');fill(fade);
  const fa=Math.round(255*(1-Math.hypot(.5,.5)/32));checkPixel('actual-star-mask-gradient',32,32,[0,0,0,fa]);
  const mask=document.createElement('canvas');mask.width=mask.height=64;const mctx=mask.getContext('2d');mctx.fillStyle=fade;mctx.fillRect(0,0,64,64);
  reset();ctx.drawImage(mask,0,0);checkPixel('gradient-real-draw-image-source',32,32,[0,0,0,fa]);
  ctx.fillStyle=g;canvas.width=64;assert('resize-resets-gradient-state',ctx.fillStyle==='#000000');
  fill(g);checkPixel('external-gradient-survives-resize',4,2,[112,0,143,255]);
  console.log('GRADIENT-JS '+count+' checks, '+failed+' failed');
})();
