globalThis.runDOMRuntimeCases=async function(){
    let count=0;const ok=(v,n)=>{count++;check('dom-runtime-'+n,v);if(!v)throw Error(n);};
    const tick=()=>Promise.resolve();
    const root=document.createElement('div');document.body.appendChild(root);
    const cn=root.childNodes,ch=root.children;
    ok(cn instanceof NodeList && !Array.isArray(cn),'nodelist-brand');
    ok(ch instanceof HTMLCollection && !(ch instanceof NodeList),'htmlcollection-brand');
    ok(cn===root.childNodes && ch===root.children,'same-object');
    ok(cn.item(0)===null && cn[0]===undefined,'empty-index');
    const text=document.createTextNode('a'),a=document.createElement('i');a.id='first';a.className='thing';
    root.append(text,a);ok(cn.length===2 && cn[0]===text && ch.length===1 && ch[0]===a,'live-children');
    ok(ch.first===a && ch.namedItem('first')===a && ch.namedItem('')===null,'named-access');
    ok(Object.keys(ch).join(',')==='0','named-not-enumerable');
    ok(Object.prototype.toString.call(cn)==='[object NodeList]','nodelist-tag');
    const query=root.querySelectorAll('.thing'),live=root.getElementsByClassName('thing');
    const b=document.createElement('i');b.className='thing';root.appendChild(b);
    ok(query instanceof NodeList && query.length===1 && live.length===2,'static-and-live-query');
    b.className='other';ok(live.length===1,'live-class-change');
    let seen=[];cn.forEach((n,i,o)=>seen.push(n===cn[i] && o===cn));ok(seen.length===3 && seen.every(Boolean),'for-each');
    ok(Array.from(cn).length===3 && [...cn.keys()].join(',')==='0,1,2' && [...cn.entries()][1][1]===a,'iterators');
    ok(Reflect.set(cn,'0',b)===false && cn[0]===text,'read-only-index');
    ok(root.getElementsByClassName('').length===0,'empty-class-query');
    root.removeChild(text);ok(cn.length===2 && cn[0]===a,'removed-live');
    let received=[],calls=0,self,observerArg;
    const mo=new MutationObserver(function(rs,o){calls++;self=this;observerArg=o;received.push(...rs);});
    mo.observe(root,{childList:true,subtree:true,attributeOldValue:true,characterDataOldValue:true});
    a.setAttribute('data-v','one');a.setAttribute('data-v','two');a.setAttribute('data-v','two');a.removeAttribute('missing');
    ok(calls===0,'mutation-not-sync');await tick();ok(calls===1 && self===mo && observerArg===mo,'microtask-delivery');
    ok(received.length===3 && received[0] instanceof MutationRecord,'attribute-records');
    ok(received[0].target===a && received[0].type==='attributes' && received[0].attributeName==='data-v','attribute-target');
    ok(received.map(x=>x.oldValue).join('|')==='|one|two','old-values-and-same-value');
    ok(received[0].addedNodes instanceof NodeList && received[0].addedNodes.length===0,'record-node-lists');
    received=[];root.appendChild(text);text.nodeValue='b';await tick();
    ok(received.length===2 && received[0].type==='childList' && received[0].addedNodes[0]===text,'insertion-record');
    ok(received[0].previousSibling===b && received[0].nextSibling===null,'insertion-siblings');
    ok(received[1].type==='characterData' && received[1].oldValue==='a','character-data');
    received=[];root.removeChild(a);a.setAttribute('data-v','detached');await tick();
    ok(received.length===2 && received[0].removedNodes[0]===a && received[1].oldValue==='two','detached-subtree-until-delivery');
    received=[];a.setAttribute('data-v','later');await tick();ok(received.length===0,'transient-cleaned');
    b.setAttribute('data-drain','x');const drained=mo.takeRecords();ok(drained.length===1 && mo.takeRecords().length===0,'take-records');await tick();ok(received.length===0,'drained-no-delivery');
    mo.observe(root,{subtree:true,attributes:true,attributeFilter:['data-only']});
    b.setAttribute('data-other','x');b.setAttribute('data-only','yes');await tick();
    ok(received.length===1 && received[0].attributeName==='data-only' && received[0].oldValue===null,'filter-and-reconfigure');
    mo.disconnect();received=[];b.setAttribute('data-only','no');await tick();ok(received.length===0,'disconnect');
    mo.observe(root,{childList:true});
    const fragment=document.createDocumentFragment(),x=document.createElement('span'),y=document.createElement('span');fragment.append(x,y);
    root.appendChild(fragment);await tick();ok(received.length===1 && received[0].addedNodes.length===2 && received[0].addedNodes[1]===y,'fragment-single-record');
    received=[];root.innerHTML='<p>fresh</p>';await tick();ok(received.length===1 && received[0].removedNodes.length===4 && received[0].addedNodes[0].tagName==='P','replace-all-record');
    mo.disconnect();
    for(const opt of [{},{attributes:false,attributeOldValue:true},{characterData:false,characterDataOldValue:true},{childList:true,attributes:false,attributeFilter:[]}]){let threw=false;try{mo.observe(root,opt);}catch(e){threw=e instanceof TypeError;}ok(threw,'invalid-observation');}
    let e=document.createEvent('Events');ok(e instanceof Event && e.type==='','legacy-event-brand');
    let threw=false;try{root.dispatchEvent(e);}catch(x){threw=x.name==='InvalidStateError';}ok(threw,'uninitialized-rejected');
    e.initEvent('legacy',true,true);let n=0;
    root.addEventListener('legacy',ev=>{n++;ev.preventDefault();ev.stopPropagation();ev.initEvent('wrong');});
    ok(root.dispatchEvent(e)===false && n===1 && e.type==='legacy','init-while-dispatch-noop');
    e.initEvent('clean');ok(!e.defaultPrevented && !e.cancelBubble && !e.isTrusted && e.target===null,'reinit-resets-flags');
    e=document.createEvent('CustomEvent');ok(e instanceof CustomEvent,'legacy-custom-brand');
    const detail={real:true};e.initCustomEvent('custom',false,true,detail);ok(e.detail===detail && e.cancelable,'legacy-custom-detail');
    root.addEventListener('custom',ev=>{ok(ev.detail===detail,'legacy-custom-delivery');});root.dispatchEvent(e);
    threw=false;try{document.createEvent('made-up');}catch(e){threw=e.name==='NotSupportedError';}ok(threw,'unsupported-interface-rejected');
    let windowLoads=0,documentLoads=0;
    const windowLoad=()=>windowLoads++,documentLoad=()=>documentLoads++;
    window.addEventListener('load',windowLoad,true);document.addEventListener('load',documentLoad,true);
    const resource=document.createElement('img');root.appendChild(resource);
    for(let i=0;i<32;i++)resource.dispatchEvent(new Event('load'));
    ok(windowLoads===0 && documentLoads===32,'resource-load-does-not-reach-window');
    window.dispatchEvent(new Event('load'));ok(windowLoads===1,'window-load-still-delivered');
    window.removeEventListener('load',windowLoad,true);document.removeEventListener('load',documentLoad,true);
    e=document.createEvent('MouseEvents');
    ok(e instanceof MouseEvent && e instanceof UIEvent,'legacy-mouse-interface');
    e.initMouseEvent('pointerdown',true,true,window,2,10,20,30,40,true,false,true,false,1,root);
    ok(e.type==='pointerdown' && e.bubbles && e.cancelable && e.view===window && e.detail===2,'legacy-mouse-base');
    ok(e.screenX===10 && e.screenY===20 && e.clientX===30 && e.clientY===40 && e.button===1 && e.relatedTarget===root,'legacy-mouse-fields');
    ok(e.getModifierState('Control') && e.getModifierState('Shift') && !e.getModifierState('Alt'),'legacy-mouse-modifiers');
    let pointer=0;root.addEventListener('pointerdown',v=>{pointer++;v.initMouseEvent('wrong');});root.dispatchEvent(e);
    ok(pointer===1 && e.type==='pointerdown','legacy-mouse-dispatch');
    e=document.createEvent('UIEvents');e.initUIEvent('resize',false,false,window,3);ok(e instanceof UIEvent && e.detail===3 && e.view===window,'legacy-ui');
    const replacement=document.createElement('div'),old=document.createElement('b');replacement.append(old);root.append(replacement);
    threw=false;try{replacement.replaceChildren(document);}catch(error){threw=error.name==='HierarchyRequestError';}
    ok(threw&&replacement.firstChild===old,'replacechildren-invalid-preserves-children');
    const convertParent=document.createElement('div'),movedAtConversion=document.createElement('i'),survivor=document.createElement('b');convertParent.append(movedAtConversion,survivor);
    threw=false;try{convertParent.replaceChildren(movedAtConversion,document);}catch(error){threw=error.name==='HierarchyRequestError';}
    ok(threw&&convertParent.childNodes.length===1&&convertParent.firstChild===survivor&&movedAtConversion.parentNode.nodeType===11,'replacechildren-invalid-conversion-keeps-unconverted-old-children');
    const replaceRecords=[],replaceObserver=new MutationObserver(rs=>replaceRecords.push(...rs));replaceObserver.observe(replacement,{childList:true});
    const replacementName='runtime-replacement-'+Date.now(),connectedCounts=[];
    customElements.define(replacementName,class extends HTMLElement{connectedCallback(){connectedCounts.push(this.parentNode.childNodes.length);}});
    const firstNew=document.createElement(replacementName),secondNew=document.createElement(replacementName);
    replacement.replaceChildren(firstNew,secondNew);
    ok(connectedCounts.join(',')==='2,2','replacechildren-ce-observes-complete-tree');
    const replacementQueue=replaceObserver.takeRecords();
    ok(replacementQueue.length===1&&replacementQueue[0].removedNodes[0]===old&&replacementQueue[0].addedNodes.length===2,'replacechildren-one-record');
    replaceObserver.disconnect();
    const replacementDoc=document.implementation.createHTMLDocument('replacement'),newHtml=replacementDoc.createElement('html');
    replacementDoc.replaceChildren(newHtml);ok(replacementDoc.childNodes.length===1&&replacementDoc.documentElement===newHtml,'replacechildren-document-replaces-old-root');
    const probe=new EventTarget(),immutable=new Event('immutable',{cancelable:true}),eventCalls=[];
    probe.addEventListener('immutable',ev=>{eventCalls.push(1);Object.defineProperty(ev,'type',{value:'other'});ev._stop=true;ev._immediate=true;});
    probe.addEventListener('immutable',()=>eventCalls.push(2));
    ok(probe.dispatchEvent(immutable)&&eventCalls.join(',')==='1,2','event-public-fields-do-not-change-dispatch');
    const forgedCancel=new Event('uncancelable');Object.defineProperty(forgedCancel,'defaultPrevented',{value:true});Object.defineProperty(forgedCancel,'cancelable',{value:true});
    forgedCancel.preventDefault();ok(probe.dispatchEvent(forgedCancel),'event-public-cancel-fields-do-not-cancel');
    const trustedDescriptor=Object.getOwnPropertyDescriptor(immutable,'isTrusted');
    ok(trustedDescriptor&&!trustedDescriptor.configurable&&!Reflect.set(immutable,'isTrusted',true)&&!immutable.isTrusted,'event-trust-unforgeable');
    const stoppedEvent=new Event('stopped');let stoppedCalls=0;probe.addEventListener('stopped',()=>stoppedCalls++);stoppedEvent.stopPropagation();probe.dispatchEvent(stoppedEvent);
    ok(stoppedCalls===0&&!stoppedEvent.cancelBubble,'event-prestopped-and-dispatch-clears-flags');
    const detachedParent=document.createElement('div'),detachedChild=document.createElement('span'),trigger=document.createElement('i');
    detachedParent.append(detachedChild);root.append(detachedParent,trigger);
    const crossObserverLog=[];
    const firstObserver=new MutationObserver(()=>{crossObserverLog.push('first');detachedChild.setAttribute('late','yes');});
    const laterObserver=new MutationObserver(rs=>{crossObserverLog.push('later');ok(rs.length===2&&rs[0].type==='childList'&&rs[1].attributeName==='late','observer-prior-callback-detached-record');});
    firstObserver.observe(trigger,{attributes:true});laterObserver.observe(detachedParent,{childList:true,attributes:true,subtree:true});
    trigger.setAttribute('start','yes');detachedChild.remove();await tick();
    ok(crossObserverLog.join(',')==='first,later','observer-creation-order-and-one-delivery');
    detachedChild.setAttribute('expired','yes');ok(laterObserver.takeRecords().length===0,'observer-transient-expires-at-own-delivery');
    firstObserver.disconnect();laterObserver.disconnect();
    root.remove();return count;
};
