globalThis.runEventHandlerCases=function(){
    let count=0;const assert=(v,n)=>{count++;check('handler-'+n,v);if(!v)throw Error(n);};
    const node=document.createElement('input');
    assert('oninput' in node && node.oninput===null,'element-feature-detection');
    assert('oninput' in document && document.oninput===null,'document-feature-detection');
    assert('oninput' in window && window.oninput===null,'window-feature-detection');
    assert(!('oninput' in document.createTextNode('x')),'not-on-text-nodes');
    let events=[],receiver,event;
    const first=()=>events.push('first'),last=()=>events.push('last');
    node.addEventListener('input',first);
    node.oninput=function(e){events.push('handler');receiver=this;event=e;};
    node.addEventListener('input',last);
    const e=new Event('input');node.dispatchEvent(e);
    assert(events.join(',')==='first,handler,last' && receiver===node && event===e,'listener-slot-and-receiver');
    events=[];node.oninput=()=>events.push('replacement');node.dispatchEvent(e);
    assert(events.join(',')==='first,replacement,last','replacement-keeps-order');
    events=[];node.oninput=null;node.dispatchEvent(e);
    assert(events.join(',')==='first,last' && node.oninput===null,'null-removes');
    events=[];node.oninput=()=>events.push('new');node.dispatchEvent(e);
    assert(events.join(',')==='first,last,new','reactivation-appends');
    node.oninput='not code';assert(node.oninput===null,'non-object-is-null');
    node.setAttribute('oninput','this.inlineCount=(this.inlineCount||0)+1');
    const fn=node.oninput;assert(typeof fn==='function' && node.oninput===fn,'inline-getter-caches');
    node.dispatchEvent(e);assert(node.inlineCount===1,'inline-runs');
    node.oninput=()=>{node.assigned=true;};
    node.setAttribute('oninput','this.inlineCount=(this.inlineCount||0)+1');node.dispatchEvent(e);
    assert(node.inlineCount===2 && !node.assigned,'same-attribute-resets-assigned-handler');
    node.removeAttribute('oninput');assert(node.oninput===null,'attribute-removal');
    node.oninput=fn;node.removeAttribute('oninput');assert(node.oninput===fn,'absent-attribute-removal-preserves-property');
    node.setAttribute('onclick','return false');
    assert(!node.dispatchEvent(new Event('click',{cancelable:true})),'inline-return-false-cancels');
    const parent=document.createElement('div');parent.innerHTML='<button onclick="this.steps.push(1)"></button>';
    const button=parent.firstChild;button.steps=[];
    button.addEventListener('click',()=>button.steps.push(2));button.dispatchEvent(new Event('click'));
    assert(button.steps.join(',')==='1,2','parsed-inline-before-listener');
    button.steps=[];button.onclick=()=>button.steps.push(3);button.dispatchEvent(new Event('click'));
    assert(button.steps.join(',')==='3,2','parsed-slot-replacement');
    const clone=button.cloneNode(true);clone.steps=[];clone.dispatchEvent(new Event('click'));
    assert(clone.steps.join(',')==='1','clone-copies-attribute-not-listeners');
    return count;
};
