globalThis.runHistoryCases = async function() {
    const assert=(ok,name)=>{check('history-'+name,ok);if(!ok)throw new Error(name);};
    const rejects=(fn,name)=>{try{fn();}catch(e){return e.name===name;}return false;};
    assert(history instanceof History&&history.state===null&&history.length===1,'initial');
    assert(rejects(()=>new History(),'TypeError'),'illegal-constructor');
    assert(rejects(()=>History.prototype.pushState.call({},null,''),'TypeError'),'brand');
    assert(rejects(()=>history.pushState(null),'TypeError'),'arity');
    assert(rejects(()=>history.go(1n),'TypeError'),'go-bigint-rejected');
    const start=location.href, data={a:1,map:new Map(),date:new Date(123)};data.self=data;data.map.set(data,data);
    history.scrollRestoration='manual';
    history.pushState(data,'','?page=1#one');data.a=2;
    assert(history.length===2&&location.search==='?page=1'&&location.hash==='#one','push-url');
    let state=history.state;
    assert(state.a===1&&state!==data&&state.self===state&&state.map.get(state)===state&&state.date.getTime()===123,'clone');
    assert(history.state===state&&history.scrollRestoration==='manual','state-identity-mode');
    state.a=3;assert(history.state.a===3,'live-state-identity');
    assert(rejects(()=>history.pushState(null,'','https://evil.invalid/'),'SecurityError'),'cross-origin');
    assert(rejects(()=>history.pushState(()=>{},''),'DataCloneError'),'function-rejected');
    const thrown={};assert((()=>{try{history.pushState({get x(){throw thrown;}},'');}catch(e){return e===thrown;}return false;})(),'getter-exception');
    assert(history.length===2,'failed-operations-atomic');
    history.replaceState({second:true},'','?page=2#two');
    assert(history.length===2&&history.state.second&&location.hash==='#two','replace');
    const events=[];
    addEventListener('hashchange',e=>events.push(['hash',e.oldURL,e.newURL]));
    const nextPop=()=>new Promise(resolve=>addEventListener('popstate',resolve,{once:true}));
    history.go=()=>{throw new Error('overridden go must not affect back/forward');};
    let pop=nextPop();history.back();let event=await pop;
    assert(event.state===null&&history.state===null&&location.href===start,'back');
    // Hashchange is delivered after popstate in the same traversal task.
    await new Promise(resolve=>setTimeout(resolve,0));
    assert(events.length===1&&events[0][1].endsWith('#two')&&events[0][2]===start,'hash-event');
    pop=nextPop();history.forward();event=await pop;
    assert(event.state.second&&event.state===history.state&&location.hash==='#two','forward');
    delete history.go;
    pop=nextPop();history.back();await pop;
    history.pushState({third:true},'','?page=3');
    assert(history.length===2&&history.state.third,'forward-discard');
    history.scrollRestoration='auto';assert(history.scrollRestoration==='auto','scroll-mode');
};
