/* Product-path regression tests: real native parsing, Attrs, script sinks,
 * shadow trees and QuickJS dynamic compilation. Not real-site acceptance. */
globalThis.runHTMLSafetyCases=function(){
    let count=0;
    function check(name,value){count++;if(!value)throw new Error('HTML safety '+name);}
    function throws(name,fn,type=TypeError){let caught=false;try{fn();}catch(e){caught=e instanceof type;}check(name,caught);}
    const HTML='http://www.w3.org/1999/xhtml',SVG='http://www.w3.org/2000/svg',MATH='http://www.w3.org/1998/Math/MathML';
    check('interfaces',typeof Sanitizer==='function'&&typeof trustedTypes==='object');
    const violation=new SecurityPolicyViolationEvent('securitypolicyviolation',{sample:'test',disposition:'report',lineNumber:-1,statusCode:65537});
    check('public violation event',violation instanceof Event&&!violation.isTrusted&&violation.sample==='test'&&violation.disposition==='report'&&violation.lineNumber===4294967295&&violation.statusCode===1);
    violation.isTrusted=true;check('violation trusted flag cannot be forged',!violation.isTrusted);
    throws('violation enum rejected',()=>new SecurityPolicyViolationEvent('securitypolicyviolation',{disposition:'bad'}));
    const permissive=new Sanitizer({}),pc=permissive.get();
    check('permissive defaults',pc.removeElements.length===0&&pc.removeAttributes.length===0&&pc.comments&&pc.javascriptURLs);
    check('copy configuration',pc!==permissive.get());pc.removeElements.push({name:'p',namespace:HTML});check('copy isolated',permissive.get().removeElements.length===0);
    const defaults=new Sanitizer().get();check('safe default lists',defaults.elements.length>=100&&defaults.attributes.length>30&&!defaults.comments&&!defaults.javascriptURLs&&!defaults.dataAttributes);
    throws('mixed elements',()=>new Sanitizer({elements:[],removeElements:[]}));
    throws('mixed attributes',()=>new Sanitizer({attributes:[],removeAttributes:[]}));
    throws('mixed PI',()=>new Sanitizer({processingInstructions:[],removeProcessingInstructions:[]}));
    throws('duplicate element',()=>new Sanitizer({elements:['p',{name:'p'}]}));
    throws('duplicate attribute',()=>new Sanitizer({attributes:['title','title']}));
    throws('primitive sequence',()=>new Sanitizer({elements:'p'}));
    throws('noniterable sequence',()=>new Sanitizer({attributes:{0:'title',length:1}}));
    throws('duplicate PI',()=>new Sanitizer({processingInstructions:['patch',{target:'patch'}]}));
    throws('overlap unwrap',()=>new Sanitizer({elements:['div'],replaceWithChildrenElements:['div']}));
    throws('nonreplaceable HTML',()=>new Sanitizer({replaceWithChildrenElements:['html']}));
    throws('nonreplaceable SVG',()=>new Sanitizer({replaceWithChildrenElements:[{name:'svg',namespace:SVG}]}));
    throws('nonreplaceable MathML',()=>new Sanitizer({replaceWithChildrenElements:[{name:'math',namespace:MATH}]}));
    throws('data without allowlist',()=>new Sanitizer({dataAttributes:true}));
    throws('data redundant',()=>new Sanitizer({attributes:['data-x'],dataAttributes:true}));
    throws('local global redundant',()=>new Sanitizer({elements:[{name:'p',attributes:['title']}],attributes:['title']}));
    throws('local removal subset',()=>new Sanitizer({elements:[{name:'p',removeAttributes:['title']}],attributes:[]}));
    throws('local mixed with remove mode',()=>new Sanitizer({elements:[{name:'p',attributes:[],removeAttributes:[]}]}));
    throws('missing name',()=>new Sanitizer({elements:[{}]}));
    throws('invalid preset',()=>new Sanitizer('other'));
    throws('sanitizer brand',()=>Sanitizer.prototype.get.call({}));
    check('mutator remove element',permissive.removeElement('script')&&!permissive.removeElement('script'));
    check('mutator allow element',permissive.allowElement('script')&&!permissive.allowElement('script'));
    check('mutator remove attribute',permissive.removeAttribute('onclick')&&!permissive.removeAttribute('onclick'));
    check('mutator allow attribute',permissive.allowAttribute('onclick')&&!permissive.allowAttribute('onclick'));
    check('mutator PI remove',permissive.removeProcessingInstruction('patch')&&!permissive.removeProcessingInstruction('patch'));
    check('mutator PI allow',permissive.allowProcessingInstruction('patch')&&!permissive.allowProcessingInstruction('patch'));
    check('mutator comments',permissive.setComments(false)&&!permissive.setComments(false)&&permissive.setComments(true));
    check('mutator javascript URLs',permissive.setJavascriptURLs(false)&&!permissive.setJavascriptURLs(false)&&permissive.setJavascriptURLs(true));
    check('mutator data remove mode',!permissive.setDataAttributes(true));
    check('remove unsafe changes',permissive.removeUnsafe()&&!permissive.removeUnsafe());
    check('baseline removes executable',permissive.get().removeElements.some(e=>e.name==='script'&&e.namespace===HTML)&&permissive.get().removeElements.some(e=>e.name==='script'&&e.namespace===SVG));
    check('baseline handler',permissive.get().removeAttributes.some(a=>a.name==='onclick')&&!permissive.get().javascriptURLs);
    const allow=new Sanitizer({elements:['p'],attributes:['title'],dataAttributes:false});
    check('allow element add',allow.allowElement({name:'b',attributes:['id']})&&!allow.allowElement({name:'b',attributes:['id']}));
    check('attribute promotion',allow.allowAttribute('id')&&!allow.allowAttribute('id')&&allow.get().elements.find(e=>e.name==='b').attributes.length===0);
    check('data mutator',allow.setDataAttributes(true)&&!allow.setDataAttributes(true));
    check('unwrap mutator',allow.replaceElementWithChildren('p')&&!allow.replaceElementWithChildren('p'));
    check('nonreplaceable mutator',!allow.replaceElementWithChildren('html'));
    const node=document.createElement('div');
    const fastNode=document.createElement('div');
    fastNode.innerHTML='<b>x</b>';check('fast string innerHTML',fastNode.firstChild.localName==='b'&&fastNode.textContent==='x');
    const fastPolicy=trustedTypes.createPolicy('t1fast',{createHTML:s=>s,createScript:s=>s});
    const fastHTML=fastPolicy.createHTML('<i>y</i>');fastHTML.toString=()=>{throw new Error('TrustedHTML stringifier must not run');};
    fastNode.innerHTML=fastHTML;check('fast path retains TrustedHTML native slot',fastNode.firstChild.localName==='i'&&fastNode.textContent==='y');
    fastNode.setAttribute('onclick',fastPolicy.createScript('void 0'));check('fast path retains TrustedScript attribute',fastNode.getAttribute('onclick')==='void 0');
    fastNode.setAttribute('title',5);check('fast normal attribute conversion',fastNode.getAttribute('title')==='5');
    check('fast path retains TrustedScript eval',eval(fastPolicy.createScript('1+1'))===2);
    const fastScript=document.createElement('script');fastScript.textContent='1';check('fast script textContent',fastScript.textContent==='1');
    const fastBeforeMeta=document.createElement('script');fastBeforeMeta.textContent='globalThis.__fastBeforeMeta=1';
    const slowBeforeMeta=document.createElement('script');slowBeforeMeta.textContent={toString(){return 'globalThis.__slowBeforeMeta=1';}};
    const attributeOrder=[];
    fastNode.setAttributeNS({toString(){attributeOrder.push('namespace');return 'urn:fast';}},{toString(){attributeOrder.push('name');return 'x:title';}},{toString(){attributeOrder.push('value');return '5';}});
    check('fast attribute coercion once and ordered',attributeOrder.join(',')==='namespace,name,value'&&fastNode.getAttributeNS('urn:fast','title')==='5');
    let invalidNameRead=false;throws('fast attribute brand before name',()=>Element.prototype.setAttribute.call({}, {toString(){invalidNameRead=true;return 'title';}},'x'));check('fast attribute invalid brand no coercion',!invalidNameRead);
    node.setHTML('<p>ignored unknown member</p>',{get runScripts(){throw new Error('Unknown SetHTMLOptions member must not be read');}});
    check('safe options ignores unknown member',node.textContent==='ignored unknown member');
    globalThis.__safetyExecuted=0;
    const attack='<p id="ok" title="yes" onclick="__safetyExecuted++" data-x="1">text</p><!--secret--><script>__safetyExecuted++</script><iframe srcdoc="<script>parent.__safetyExecuted++<\/script>"></iframe><object data="x"></object><svg><script>__safetyExecuted++</script><use href="#x"></use><a href="java&#10;script:__safetyExecuted++">link</a></svg>';
    node.setHTML(attack);
    check('safe parsing inert',__safetyExecuted===0);
    check('safe unsafe elements',!node.querySelector('script')&&!node.querySelector('iframe')&&!node.querySelector('object')&&!node.querySelector('use'));
    check('safe event removed',!node.querySelector('p').hasAttribute('onclick'));
    check('safe default id removed',!node.querySelector('p').hasAttribute('id'));
    check('safe global kept',node.querySelector('p').getAttribute('title')==='yes');
    check('safe comments removed',!Array.from(node.childNodes).some(n=>n.nodeType===8));
    check('safe data removed',!node.querySelector('p').hasAttribute('data-x'));
    check('safe SVG URL',!node.querySelector('a').hasAttribute('href'));
    node.setHTML('<a href=" \tjava&#13;script:bad()">a</a><button formaction="javascript:bad()">b</button>',{sanitizer:{}});
    check('safe custom permissive URL still removed',!node.querySelector('a').hasAttribute('href')&&!node.querySelector('button').hasAttribute('formaction'));
    node.setHTML('<template><img onerror="bad()" src=x><script>bad()</script></template>',{sanitizer:{}});
    check('template recursion',!node.querySelector('template').content.querySelector('script')&&!node.querySelector('template').content.querySelector('img').hasAttribute('onerror'));
    node.setHTMLUnsafe('<div><b id=gone>b</b><i title=kept>i</i></div><!--keep--><?patch name="x">',{sanitizer:{replaceWithChildrenElements:['div'],removeElements:['b'],removeAttributes:['id']}});
    check('unwrap keeps children',node.firstElementChild.localName==='i'&&node.firstElementChild.getAttribute('title')==='kept');
    check('permissive comments PI',Array.from(node.childNodes).some(n=>n.nodeType===8)&&Array.from(node.childNodes).some(n=>n.nodeType===7));
    node.setHTMLUnsafe('<p title=yes id=no data-a=ok>p</p><b>b</b>',{sanitizer:{elements:['p'],attributes:['title'],dataAttributes:false}});
    check('custom allowlist',node.children.length===1&&node.firstChild.getAttribute('title')==='yes'&&!node.firstChild.hasAttribute('id')&&!node.firstChild.hasAttribute('data-a'));
    const old=node.innerHTML;throws('failed config no mutation',()=>node.setHTMLUnsafe('<em>bad</em>',{sanitizer:{elements:[],removeElements:[]}}));check('failed config atomic',node.innerHTML===old);
    const parsed=Document.parseHTML('<p onclick=bad()>hello</p><script>bad()</script>');
    const noScriptsOption=Document.parseHTMLUnsafe('<p>inert</p>',{get runScripts(){throw new Error('Unknown ParseHTMLUnsafeOptions member must not be read');}});
    check('static parser ignores unknown runScripts',noScriptsOption.body.textContent==='inert');
    check('static safe native document',parsed.nodeType===9&&parsed.body.textContent==='hello'&&!parsed.querySelector('script'));
    const unsafe=Document.parseHTMLUnsafe('<p onclick=bad()>hello</p><script>__safetyExecuted++</script>');
    check('static unsafe retains inert',unsafe.querySelector('script')!==null&&unsafe.querySelector('p').hasAttribute('onclick')&&__safetyExecuted===0);
    const policy=trustedTypes.createPolicy('html-safety-test',{createHTML:(s,prefix='')=>prefix+s,createScript:s=>s,createScriptURL:s=>s,createParserOptions:o=>o});
    check('policy name',policy.name==='html-safety-test');
    const html=policy.createHTML('<b>trusted</b>'),code=policy.createScript('7+5'),url=policy.createScriptURL('/safe.js');
    check('genuine HTML',trustedTypes.isHTML(html)&&!trustedTypes.isHTML(code)&&!trustedTypes.isHTML({}));
    check('genuine script',trustedTypes.isScript(code)&&!trustedTypes.isScript(html));
    check('genuine script URL',trustedTypes.isScriptURL(url)&&!trustedTypes.isScriptURL(html));
    check('stringifier',String(html)==='<b>trusted</b>'&&String(code)==='7+5'&&String(url)==='/safe.js');
    check('JSON stringifier',JSON.stringify(html)==='"<b>trusted</b>"');
    throws('constructor HTML',()=>new TrustedHTML());
    throws('constructor script',()=>new TrustedScript());
    throws('constructor URL',()=>new TrustedScriptURL());
    throws('constructor parser options',()=>new TrustedHTMLParserOptions());
    throws('constructor policy',()=>new TrustedTypePolicy());
    throws('constructor factory',()=>new TrustedTypePolicyFactory());
    const forged=Object.create(TrustedHTML.prototype);check('forged not HTML',!trustedTypes.isHTML(forged));throws('forged data inaccessible',()=>String(forged));
    throws('cross type stringifier',()=>TrustedHTML.prototype.toString.call(code));
    html.data='forged';html.toString=()=>'<script>bad()</script>';node.innerHTML=html;check('native slot used despite stringifier override',node.firstChild.localName==='b'&&node.textContent==='trusted');
    node.insertAdjacentHTML('beforeend',policy.createHTML('<i>more</i>'));check('adjacent trusted',node.children.length===2);
    check('policy extra args',String(policy.createHTML('x','pre'))==='prex');
    const nullPolicy=trustedTypes.createPolicy('html-safety-null',{createHTML:()=>null,createScript:()=>undefined,createParserOptions:()=>null});
    check('named null means empty',String(nullPolicy.createHTML('x'))===''&&String(nullPolicy.createScript('x'))==='');
    throws('parser null rejected',()=>nullPolicy.createParserOptions({}));
    throws('missing callback',()=>trustedTypes.createPolicy('html-safety-empty',{}).createScript('x'));
    throws('invalid callback',()=>trustedTypes.createPolicy('html-safety-invalid',{createHTML:2}));
    const configSource=new Sanitizer({removeElements:['script']}),opts=policy.createParserOptions({sanitizer:configSource});configSource.allowElement('script');
    node.setHTMLUnsafe('<script>bad()</script><p>kept</p>',opts);check('trusted options snapshot',!node.querySelector('script')&&node.querySelector('p')!==null);
    check('attribute script URL type',trustedTypes.getAttributeType('SCRIPT','SRC')==='TrustedScriptURL');
    check('attribute event type',trustedTypes.getAttributeType('div','onclick')==='TrustedScript');
    check('attribute namespaced not event',trustedTypes.getAttributeType('div','onclick',HTML,'urn:x')===null);
    check('attribute custom namespace not event',trustedTypes.getAttributeType('div','onclick','urn:custom')===null);
    check('attribute srcdoc type',trustedTypes.getAttributeType('iframe','srcdoc')==='TrustedHTML');
    check('property markup type',trustedTypes.getPropertyType('div','innerHTML')==='TrustedHTML');
    check('property script text type',trustedTypes.getPropertyType('script','textContent')==='TrustedScript');
    check('property normal null',trustedTypes.getPropertyType('div','title')===null);
    check('emptyHTML same object',trustedTypes.emptyHTML===trustedTypes.emptyHTML&&String(trustedTypes.emptyHTML)==='');
    check('emptyScript native eval',eval(trustedTypes.emptyScript)===undefined);
    check('native eval trusted',eval(code)===12);
    function lexical(){const privateValue=40;return eval(policy.createScript('privateValue+2'));}
    check('direct eval retains lexical scope',lexical()===42);
    const object={x:1};check('non-string eval preserves identity',eval(object)===object);
    check('Function trusted',Function(policy.createScript('return 42'))()===42);
    check('Function trusted args',Function(policy.createScript('a'),policy.createScript('return a+1'))(2)===3);
    const alteredCode=policy.createScript('return 71');alteredCode.toString=()=>{throw new Error('TrustedScript stringifier override must not run');};
    check('Function native payload despite override',Function(alteredCode)()===71);
    const script=document.createElement('script');script.text=policy.createScript('void 0');script.src=url;check('script reflected trusted',script.text==='void 0'&&script.getAttribute('src')==='/safe.js');
    const frame=document.createElement('iframe');frame.srcdoc=policy.createHTML('<p>frame</p>');check('srcdoc trusted',frame.getAttribute('srcdoc')==='<p>frame</p>');
    const attached=document.createAttribute('onclick');attached.value='void 0';node.setAttributeNode(attached);check('attribute node attachment',node.getAttributeNode('onclick')===attached);
    const mapAttr=document.createAttribute('onload');mapAttr.value='void 0';node.attributes.setNamedItem(mapAttr);check('attribute map attachment',node.getAttributeNode('onload')===mapAttr);
    throws('trusted values not cloneable',()=>structuredClone(html),DOMException);
    throws('sanitizer not cloneable',()=>structuredClone(permissive),DOMException);
    const shadowHost=document.createElement('div'),shadow=shadowHost.attachShadow({mode:'closed',serializable:true});
    shadow.setHTML('<p onclick=bad()>shadow</p><script>bad()</script>');check('closed shadow safe',shadow.firstChild.textContent==='shadow'&&!shadow.firstChild.hasAttribute('onclick')&&!shadow.querySelector('script'));
    const declarative=document.createElement('div');
    declarative.setHTML('<template shadowrootmode="open"><p onclick=bad()>declarative</p><script>bad()</script></template>',{sanitizer:{}});
    check('declarative context shadow sanitized',declarative.shadowRoot!==null&&!declarative.shadowRoot.querySelector('script')&&!declarative.shadowRoot.querySelector('p').hasAttribute('onclick'));
    check('getHTML without shadow',shadowHost.getHTML()==='');
    check('getHTML selected closed shadow',shadowHost.getHTML({shadowRoots:[shadow]}).includes('shadowrootmode="closed"'));
    check('getHTML serializable shadow',shadowHost.getHTML({serializableShadowRoots:true}).includes('shadow'));
    throws('getHTML invalid shadow list',()=>shadowHost.getHTML({shadowRoots:[node]}));
    const fastMeta=document.createElement('meta');fastMeta.setAttribute('http-equiv','Content-Security-Policy');fastMeta.setAttribute('content',"require-trusted-types-for 'script'");document.head.appendChild(fastMeta);
    throws('fast string observes later meta',()=>{fastNode.innerHTML='<u>blocked</u>';});check('later meta failure retains HTML',fastNode.firstChild.localName==='i');
    throws('fast eval observes later meta',()=>eval('1+1'));
    throws('fast script setter observes later meta',()=>{document.createElement('script').textContent='1';});
    document.body.appendChild(fastBeforeMeta);document.body.appendChild(slowBeforeMeta);
    check('fast and slow admitted text survive later meta',globalThis.__fastBeforeMeta===1&&globalThis.__slowBeforeMeta===1);
    delete globalThis.__fastBeforeMeta;delete globalThis.__slowBeforeMeta;
    delete globalThis.__safetyExecuted;
    return count;
};
