/* New web_live ImageBitmap boundary: real native pixels, not a mock codec. */
(async()=>{
    let count=0;
    function ck(name,pass){count++;console.log((pass?'OK bitmap ':'FAIL bitmap ')+name);}
    function throws(fn,name){try{fn();return false;}catch(error){return error&&error.name===name;}}
    async function rejects(fn,name){try{await fn();return false;}catch(error){return error&&error.name===name;}}
    function canvas(w,h){const c=document.createElement('canvas');c.width=w;c.height=h;return c;}
    function pixel(bitmap,x=0,y=0){const c=canvas(bitmap.width,bitmap.height),g=c.getContext('2d');g.imageSmoothingEnabled=false;g.drawImage(bitmap,0,0);return Array.from(g.getImageData(x,y,1,1).data);}
    function equal(actual,expected){return actual.length===expected.length&&actual.every((v,i)=>v===expected[i]);}
    const rgba=new Uint8ClampedArray([255,0,0,255,0,255,0,128,0,0,255,255,255,255,255,0]);
    const data=new ImageData(rgba,2,2),source=canvas(2,2),g=source.getContext('2d');g.putImageData(data,0,0);
    ck('exposed-real-window-api',typeof createImageBitmap==='function'&&typeof ImageBitmap==='function');
    ck('illegal-constructor',throws(()=>new ImageBitmap(),'TypeError'));
    const width=Object.getOwnPropertyDescriptor(ImageBitmap.prototype,'width').get;
    const height=Object.getOwnPropertyDescriptor(ImageBitmap.prototype,'height').get;
    ck('width-brand',throws(()=>width.call({}),'TypeError'));
    ck('height-brand',throws(()=>height.call({}),'TypeError'));
    ck('close-brand',throws(()=>ImageBitmap.prototype.close.call({}),'TypeError'));
    let settled=false;const pending=createImageBitmap(source);pending.then(()=>{settled=true;});
    ck('promise-and-async-result',pending instanceof Promise&&!settled);
    const bitmap=await pending;
    ck('instance-prototype-tag',bitmap instanceof ImageBitmap&&Object.getPrototypeOf(bitmap)===ImageBitmap.prototype&&Object.prototype.toString.call(bitmap)==='[object ImageBitmap]');
    ck('native-natural-dimensions',bitmap.width===2&&bitmap.height===2);
    ck('native-red-rgba',equal(pixel(bitmap),[255,0,0,255]));
    ck('native-straight-alpha',equal(pixel(bitmap,1,0),[0,255,0,128]));
    ck('native-transparent-alpha',pixel(bitmap,1,1)[3]===0);
    source.width=1;source.height=1;
    ck('source-resize-does-not-invalidate',bitmap.width===2&&bitmap.height===2&&equal(pixel(bitmap,0,1),[0,0,255,255]));
    const snapshot=canvas(1,1),sg=snapshot.getContext('2d');sg.fillStyle='red';sg.fillRect(0,0,1,1);
    const beforeMutation=createImageBitmap(snapshot);sg.fillStyle='blue';sg.fillRect(0,0,1,1);
    const stable=await beforeMutation;
    ck('canvas-snapshot-at-call',equal(pixel(stable),[255,0,0,255]));
    const dataPending=createImageBitmap(data);rgba.fill(0);const dataBitmap=await dataPending;
    ck('image-data-snapshot-at-call',equal(pixel(dataBitmap),[255,0,0,255]));
    const backing=new Uint8ClampedArray([99,99,99,99,17,31,47,255,98,98,98,98]);
    const offsetBitmap=await createImageBitmap(new ImageData(backing.subarray(4,8),1,1));
    ck('image-data-byte-offset',equal(pixel(offsetBitmap),[17,31,47,255]));
    const copied=await createImageBitmap(bitmap);bitmap.close();
    ck('clone-independent-of-close',copied.width===2&&equal(pixel(copied,0,1),[0,0,255,255]));
    ck('closed-dimensions-zero',bitmap.width===0&&bitmap.height===0);
    ck('close-idempotent-undefined',bitmap.close()===undefined&&bitmap.close()===undefined);
    ck('closed-draw-invalid-state',throws(()=>g.drawImage(bitmap,0,0),'InvalidStateError'));
    ck('closed-clone-rejects',await rejects(()=>createImageBitmap(bitmap),'InvalidStateError'));
    ck('prototype-only-brand-rejected',await rejects(()=>createImageBitmap(Object.create(ImageBitmap.prototype)),'TypeError'));
    ck('unsupported-serialization-explicit',throws(()=>structuredClone(copied),'DataCloneError'));
    ck('unsupported-transfer-explicit',throws(()=>structuredClone(copied,{transfer:[copied]}),'DataCloneError')&&copied.width===2);
    const crop=await createImageBitmap(copied,1,0,1,1);
    ck('crop-native-green-alpha',crop.width===1&&crop.height===1&&equal(pixel(crop),[0,255,0,128]));
    const negative=await createImageBitmap(copied,2,2,-2,-2);
    ck('negative-crop-does-not-flip',negative.width===2&&negative.height===2&&equal(pixel(negative),[255,0,0,255]));
    const outside=await createImageBitmap(copied,-1,-1,3,3,{resizeQuality:'pixelated'});
    ck('outside-crop-keeps-size',outside.width===3&&outside.height===3);
    ck('outside-crop-transparent-black',equal(pixel(outside),[0,0,0,0]));
    ck('outside-crop-source-alignment',equal(pixel(outside,1,1),[255,0,0,255]));
    const noOverlap=await createImageBitmap(copied,10,10,1,1);
    ck('nonoverlap-transparent',equal(pixel(noOverlap),[0,0,0,0]));
    ck('zero-crop-width-range',await rejects(()=>createImageBitmap(copied,0,0,0,1),'RangeError'));
    ck('zero-crop-height-range',await rejects(()=>createImageBitmap(copied,0,0,1,0),'RangeError'));
    ck('crop-long-truncation',equal(pixel(await createImageBitmap(copied,.9,.9,1.9,1.9)),[255,0,0,255]));
    ck('crop-long-wrap',equal(pixel(await createImageBitmap(copied,4294967296,0,1,1)),[255,0,0,255]));
    ck('crop-bigint-type',await rejects(()=>createImageBitmap(copied,0n,0,1,1),'TypeError'));
    const nearest=await createImageBitmap(copied,{resizeWidth:4,resizeHeight:4,resizeQuality:'pixelated'});
    ck('resize-two-dimensions',nearest.width===4&&nearest.height===4);
    ck('nearest-resize-pixels',equal(pixel(nearest,0,0),[255,0,0,255])&&equal(pixel(nearest,2,0),[0,255,0,128]));
    const widthOnly=await createImageBitmap(copied,0,0,2,1,{resizeWidth:3,resizeQuality:'pixelated'});
    ck('aspect-height-ceil',widthOnly.width===3&&widthOnly.height===2);
    const heightOnly=await createImageBitmap(copied,0,0,1,2,{resizeHeight:3,resizeQuality:'pixelated'});
    ck('aspect-width-ceil',heightOnly.width===2&&heightOnly.height===3);
    const flipped=await createImageBitmap(copied,{imageOrientation:'flipY'});
    ck('flip-y-real-pixels',equal(pixel(flipped),[0,0,255,255])&&equal(pixel(flipped,0,1),[255,0,0,255]));
    const edge=new ImageData(new Uint8ClampedArray([255,0,0,255,0,0,255,0]),2,1);
    const smooth=await createImageBitmap(edge,{resizeWidth:4,resizeQuality:'low'});
    const smoothPixel=pixel(smooth,1,0);
    ck('low-resize-associated-alpha',smoothPixel[0]===255&&smoothPixel[1]===0&&smoothPixel[2]===0&&smoothPixel[3]>=190&&smoothPixel[3]<=192);
    const none=await createImageBitmap(edge,{premultiplyAlpha:'none',colorSpaceConversion:'none'});
    ck('straight-srgb-none-supported',equal(pixel(none),[255,0,0,255]));
    ck('zero-resize-invalid-state',await rejects(()=>createImageBitmap(copied,{resizeWidth:0}),'InvalidStateError'));
    ck('negative-resize-enforce-range',await rejects(()=>createImageBitmap(copied,{resizeHeight:-1}),'TypeError'));
    ck('nonfinite-resize-enforce-range',await rejects(()=>createImageBitmap(copied,{resizeWidth:Infinity}),'TypeError'));
    ck('unsigned-long-resize-range',await rejects(()=>createImageBitmap(copied,{resizeWidth:4294967296}),'TypeError'));
    ck('native-size-representation-reject',await rejects(()=>createImageBitmap(copied,{resizeWidth:4294967295,resizeHeight:2}),'RangeError'));
    ck('enum-orientation-reject',await rejects(()=>createImageBitmap(copied,{imageOrientation:'none'}),'TypeError'));
    ck('enum-alpha-reject',await rejects(()=>createImageBitmap(copied,{premultiplyAlpha:'invalid'}),'TypeError'));
    ck('enum-colorspace-reject',await rejects(()=>createImageBitmap(copied,{colorSpaceConversion:'invalid'}),'TypeError'));
    ck('enum-quality-reject',await rejects(()=>createImageBitmap(copied,{resizeQuality:'invalid'}),'TypeError'));
    ck('explicit-premultiply-unsupported',await rejects(()=>createImageBitmap(copied,{premultiplyAlpha:'premultiply'}),'NotSupportedError'));
    ck('higher-quality-unsupported',await rejects(()=>createImageBitmap(copied,{resizeQuality:'high'}),'NotSupportedError'));
    ck('primitive-options-reject',await rejects(()=>createImageBitmap(copied,1),'TypeError'));
    ck('missing-source-promise-reject',await rejects(()=>createImageBitmap(),'TypeError'));
    ck('source-object-brand-reject',await rejects(()=>createImageBitmap({width:1,height:1}),'TypeError'));
    ck('canvas-prototype-spoof-reject',await rejects(()=>createImageBitmap(Object.create(HTMLCanvasElement.prototype)),'TypeError'));
    ck('video-source-unsupported',await rejects(()=>createImageBitmap(document.createElement('video')),'NotSupportedError'));
    let order=[];const opts={};for(const key of ['colorSpaceConversion','imageOrientation','premultiplyAlpha','resizeHeight','resizeQuality','resizeWidth'])Object.defineProperty(opts,key,{get(){order.push(key);return undefined;}});
    const converted=await createImageBitmap(copied,opts);
    ck('dictionary-conversion-order',order.join(',')==='colorSpaceConversion,imageOrientation,premultiplyAlpha,resizeHeight,resizeQuality,resizeWidth'&&converted.width===2);
    let touched=false;
    ck('source-union-converts-first',await rejects(()=>createImageBitmap({}, {get imageOrientation(){touched=true;return 'flipY';}}),'TypeError')&&!touched);
    let rejectedFalsy=false;try{await createImageBitmap(copied,{get imageOrientation(){throw undefined;}});}catch(error){rejectedFalsy=error===undefined;}
    ck('falsy-author-exception-preserved',rejectedFalsy);
    const mutate=canvas(2,1),mg=mutate.getContext('2d');mg.fillStyle='red';mg.fillRect(0,0,2,1);
    const optionSnapshot=await createImageBitmap(mutate,{get imageOrientation(){mutate.width=1;mg.fillStyle='blue';mg.fillRect(0,0,1,1);return 'from-image';}});
    ck('borrow-after-author-conversion',optionSnapshot.width===1&&equal(pixel(optionSnapshot),[0,0,255,255]));
    const closeByOption=await createImageBitmap(copied);
    ck('close-during-option-reject',await rejects(()=>createImageBitmap(closeByOption,{get imageOrientation(){closeByOption.close();return 'from-image';}}),'InvalidStateError'));
    const detached=new ImageData(1,1);structuredClone(detached.data.buffer,{transfer:[detached.data.buffer]});
    ck('detached-image-data-reject',await rejects(()=>createImageBitmap(detached),'InvalidStateError'));
    const detachByOption=new ImageData(1,1);
    ck('detach-during-options-reject',await rejects(()=>createImageBitmap(detachByOption,{get imageOrientation(){structuredClone(detachByOption.data.buffer,{transfer:[detachByOption.data.buffer]});return 'from-image';}}),'InvalidStateError'));
    const empty=canvas(0,1);
    ck('empty-canvas-reject',await rejects(()=>createImageBitmap(empty),'InvalidStateError'));
    const broken=new Image();broken.src='data:image/png,invalid';
    ck('broken-image-reject',await rejects(()=>createImageBitmap(broken),'InvalidStateError'));
    const notLoaded=new Image();notLoaded.src='https://bitmap.test/pending.png';
    ck('pending-image-reject',await rejects(()=>createImageBitmap(notLoaded),'InvalidStateError'));
    const pngSource=canvas(2,2);pngSource.getContext('2d').drawImage(copied,0,0);
    const blob=await new Promise(resolve=>pngSource.toBlob(resolve));
    ck('real-encoded-png-blob',blob instanceof Blob&&blob.type==='image/png'&&blob.size>16);
    const decoded=await createImageBitmap(blob);
    ck('blob-real-decoder-dimensions',decoded.width===2&&decoded.height===2);
    ck('blob-real-decoder-pixels',equal(pixel(decoded),[255,0,0,255])&&equal(pixel(decoded,1,0),[0,255,0,128]));
    const url=URL.createObjectURL(blob);URL.revokeObjectURL(url);
    const retained=await createImageBitmap(blob);
    ck('blob-survives-object-url-revoke',retained.width===2&&equal(pixel(retained),[255,0,0,255]));
    ck('empty-blob-reject',await rejects(()=>createImageBitmap(new Blob([])),'InvalidStateError'));
    ck('invalid-encoded-bytes-reject',await rejects(()=>createImageBitmap(new Blob(['not an image'],{type:'image/png'})),'InvalidStateError'));
    const encoded=await blob.arrayBuffer();
    ck('truncated-png-reject',await rejects(()=>createImageBitmap(new Blob([encoded.slice(0,12)])),'InvalidStateError'));
    ck('svg-blob-explicitly-unsupported',await rejects(()=>createImageBitmap(new Blob(['<svg xmlns="http://www.w3.org/2000/svg" width="1" height="1"/>'],{type:'image/svg+xml'})),'NotSupportedError'));
    const transformed=canvas(4,4),tg=transformed.getContext('2d');tg.imageSmoothingEnabled=false;
    tg.setTransform(2,0,0,2,0,0);tg.globalAlpha=.5;tg.drawImage(decoded,0,0,1,1,0,0,1,1);
    ck('draw-bitmap-nine-arg-affine-alpha',equal(Array.from(tg.getImageData(1,1,1,1).data),[255,0,0,128])&&tg.getImageData(2,2,1,1).data[3]===0);
    tg.reset();tg.imageSmoothingEnabled=false;tg.drawImage(decoded,0,0,4,4);
    ck('draw-bitmap-five-arg',equal(Array.from(tg.getImageData(0,0,1,1).data),[255,0,0,255]));
    ck('bitmap-not-canvas-context',throws(()=>HTMLCanvasElement.prototype.getContext.call(decoded,'2d'),'TypeError'));
    const cleanImage=new Image();cleanImage.src='data:image/png;base64,'+btoa(String.fromCharCode(...new Uint8Array(encoded)));
    const cleanImageBitmap=await createImageBitmap(cleanImage);
    ck('loaded-html-image-real-pixels',equal(pixel(cleanImageBitmap),[255,0,0,255]));
    const networkImage=new Image(),load=new Promise((resolve,reject)=>{networkImage.onload=resolve;networkImage.onerror=reject;});networkImage.src='https://bitmap.test/fixture.png';await load;
    const tainted=await createImageBitmap(networkImage),tc=canvas(2,2),tx=tc.getContext('2d');tx.drawImage(tainted,0,0);
    ck('network-image-taint-inherited',throws(()=>tx.getImageData(0,0,1,1),'SecurityError'));
    const taintedClone=await createImageBitmap(tainted),taintedCanvas=await createImageBitmap(tc),target=canvas(2,2),targetContext=target.getContext('2d');targetContext.drawImage(taintedClone,0,0);
    ck('bitmap-clone-taint-inherited',throws(()=>targetContext.getImageData(0,0,1,1),'SecurityError'));
    target.width=2;targetContext.drawImage(taintedCanvas,0,0);
    ck('canvas-snapshot-taint-inherited',throws(()=>targetContext.getImageData(0,0,1,1),'SecurityError'));
    const typedClone=await createImageBitmap(dataBitmap);
    ck('clean-bitmap-read-remains-clean',equal(pixel(typedClone),[255,0,0,255]));
    // Repeat creation only to test owning lifetimes, not another acceptance run.
    const live=[];for(let i=0;i<16;i++)live.push(await createImageBitmap(decoded));for(const value of live)value.close();
    ck('multiple-close-lifetimes',live.every(value=>value.width===0&&value.height===0)&&decoded.width===2);
    for(const value of [stable,dataBitmap,offsetBitmap,copied,crop,negative,outside,noOverlap,nearest,widthOnly,heightOnly,flipped,smooth,none,converted,optionSnapshot,decoded,retained,cleanImageBitmap,tainted,taintedClone,taintedCanvas,typedClone])value.close();
    console.log('BITMAP-DONE '+count);
})().catch(error=>console.error('BITMAP-FATAL '+(error&&error.name)+': '+(error&&error.message)));
