async function runInnerTextCases(){
    let count=0;const assert=(value,name)=>{count++;check('inner-text-'+name,!!value);if(!value)throw new Error(name);};
    const equal=(actual,expected,name)=>assert(actual===expected,name+': '+JSON.stringify(actual));
    const throws=(call,name)=>{let error;try{call();}catch(e){error=e;}assert(error instanceof TypeError,name);};
    const descriptor=Object.getOwnPropertyDescriptor(HTMLElement.prototype,'innerText');
    assert(descriptor&&descriptor.enumerable&&descriptor.configurable,'descriptor');
    throws(()=>descriptor.get.call({}),'fake-getter');throws(()=>descriptor.set.call({},'x'),'fake-setter');
    throws(()=>descriptor.get.call(document),'document-brand');
    throws(()=>descriptor.get.call(document.createElementNS('http://www.w3.org/2000/svg','svg')),'foreign-brand');
    const target=document.createElement('div');document.body.appendChild(target);
    target.innerHTML='  a <span> b </span>  c  ';equal(target.innerText,'a b c','inline-collapse');
    equal(target.textContent,'  a  b   c  ','not-text-content-alias');
    target.innerHTML='a<span style="display:none">hidden</span>b';equal(target.innerText,'ab','display-none-child');
    target.innerHTML='a<span style="visibility:hidden">hidden<span style="visibility:visible">shown</span></span>b';
    equal(target.innerText,'ashownb','visibility-visible-descendant');
    target.innerHTML=' a <br> b<br><br>';equal(target.innerText,'a\nb\n\n','literal-breaks');
    target.innerHTML='a<wbr>b';equal(target.innerText,'ab','wbr-not-literal-break');
    target.innerHTML='a<span style="display:none"><br></span>b';equal(target.innerText,'ab','hidden-ancestor-br-exclusion');
    target.innerHTML='a<br style="display:none">b';equal(target.innerText,'ab','hidden-br-exclusion');
    target.innerHTML='<div>a</div><div>b</div>';equal(target.innerText,'a\nb','required-block-breaks');
    target.innerHTML='<p>a</p><p>b</p>';equal(target.innerText,'a\n\nb','required-paragraph-breaks');
    target.innerHTML='a<p></p>b';equal(target.innerText,'a\n\nb','empty-paragraph-boundary');
    target.innerHTML='<span style="white-space:pre"> a  b\n c </span>';equal(target.innerText,' a  b\n c ','pre-preserves');
    target.innerHTML='<span style="white-space:pre-line"> a  b\n c </span>';equal(target.innerText,'a b\nc','pre-line');
    target.innerHTML='<span style="text-transform:uppercase">aBc</span>';equal(target.innerText,'ABC','native-transform');
    target.innerHTML='<span style="display:contents"><span>x</span>y</span>';equal(target.innerText,'xy','contents-descendant');
    target.innerHTML='<style>.ignored{color:red}</style><script>/* invisible script */<'+'/script>visible';
    equal(target.innerText,'visible','nonrendered-script-style');
    target.style.display='none';equal(target.innerText,target.textContent,'hidden-target-fallback');
    target.style.display='block';target.innerHTML='new';equal(target.innerText,'new','live-style-change');
    const ancestor=document.createElement('div');ancestor.style.display='none';ancestor.appendChild(target);document.body.appendChild(ancestor);
    target.innerHTML=' a<br> b <span style="display:none"> c</span>';
    equal(target.innerText,' a b  c','hidden-ancestor-fallback');ancestor.remove();
    equal(target.innerText,' a b  c','detached-fallback');document.body.appendChild(target);
    target.innerHTML='<table><tbody><tr><td>a</td><td>b</td></tr><tr><td>c</td><td>d</td></tr></tbody></table>';
    equal(target.innerText,'a\tb\nc\td','native-table-separators');
    target.innerText='a\r\nb\rc\n\nd';
    equal(target.innerText,'a\nb\nc\n\nd','setter-breaks');
    assert(target.querySelectorAll('br').length===4,'setter-real-br-nodes');equal(target.textContent,'abcd','setter-text-content');
    target.innerText='<b>&value</b>';equal(target.innerText,'<b>&value</b>','setter-no-markup');
    assert(!target.querySelector('b'),'setter-no-element');target.innerText=null;equal(target.innerText,'null','setter-domstring-null');
    target.innerText='';assert(target.childNodes.length===0,'setter-empty-replace-all');
    const inert=document.implementation.createHTMLDocument('inert'),inertTarget=inert.createElement('div');
    inertTarget.innerHTML=' a<br> b';inert.body.appendChild(inertTarget);equal(descriptor.get.call(inertTarget),' a b','inert-fallback');
    const frame=document.createElement('iframe');document.body.appendChild(frame);
    const child=frame.contentDocument;child.open();child.write('<style>.owner{text-transform:uppercase}</style><body>');child.close();
    target.className='owner';target.textContent='owner';child.body.appendChild(target);
    equal(descriptor.get.call(target),'OWNER','adopted-owner-document-layout');
    assert(target.ownerDocument===child,'adopted-owner-document');
    frame.remove();equal(descriptor.get.call(target),'owner','retired-document-fallback');
    return count;
}
