/* Supplemental native task/clone regression, not public-site acceptance. */
async function runMessagingCases(){
    let count=0;
    const t=(name,ok)=>{count++;check('messaging-'+name,ok);};
    const throws=(name,fn,error)=>{let caught;try{fn();}catch(e){caught=e;}t(name,caught&&caught.name===error);};
    const wait=()=>new Promise(r=>setTimeout(r,12));
    const once=port=>new Promise(r=>{port.onmessage=r;});
    const c=new MessageChannel();
    t('interfaces',c.port1 instanceof MessagePort&&c.port1 instanceof EventTarget&&c.port1!==c.port2&&c.port1===c.port1);
    throws('illegal-port',()=>new MessagePort(),'TypeError');
    throws('illegal-brand',()=>MessagePort.prototype.start.call({}),'TypeError');
    throws('uncloneable-port',()=>structuredClone(c.port1),'DataCloneError');
    throws('uncloneable-channel',()=>structuredClone(c),'DataCloneError');
    throws('self-transfer',()=>c.port1.postMessage({},[c.port1]),'DataCloneError');
    throws('duplicate-transfer',()=>c.port1.postMessage({},[c.port2,c.port2]),'DataCloneError');
    let got=0;const order=[];
    c.port2.addEventListener('message',e=>{got++;order.push(e.data.n);queueMicrotask(()=>order.push('micro'+e.data.n));});
    const original={n:1};c.port1.postMessage(original);original.n=9;
    c.port1.postMessage({n:2});t('not-sync',got===0);await wait();t('disabled-queue',got===0);
    c.port2.start();await wait();t('fifo-microtasks',order.join(',')==='1,micro1,2,micro2');
    let eventPromise=once(c.port2);c.port1.postMessage({cycle:null});const basic=await eventPromise;
    t('event-interface',basic instanceof MessageEvent&&basic.target===c.port2&&basic.isTrusted);
    t('port-event-fields',basic.origin===''&&basic.source===null&&basic.lastEventId===''&&basic.ports.length===0&&Object.isFrozen(basic.ports));
    const cycle={};cycle.self=cycle;eventPromise=once(c.port2);c.port1.postMessage(cycle);
    const cyc=(await eventPromise).data;t('clone-cycle',cyc!==cycle&&cyc.self===cyc);
    const buf=new Uint8Array([1,2,3]);eventPromise=once(c.port2);c.port1.postMessage({view:buf,buffer:buf.buffer},{transfer:[buf.buffer]});
    t('buffer-detached',buf.byteLength===0);const binary=(await eventPromise).data;
    t('buffer-alias',binary.view.buffer===binary.buffer&&binary.view[2]===3);
    const atomic=new ArrayBuffer(4),bad=new ArrayBuffer(1);structuredClone(bad,{transfer:[bad]});
    throws('transfer-atomic',()=>structuredClone({}, {transfer:[atomic,bad]}),'DataCloneError');t('atomic-buffer-retained',atomic.byteLength===4);
    const safe=new MessageChannel(),safeBuffer=new ArrayBuffer(2);
    throws('failed-payload',()=>c.port1.postMessage({fn(){}},[safe.port1,safeBuffer]),'DataCloneError');
    eventPromise=once(safe.port2);safe.port1.postMessage('still-live');t('failed-transfer-port-live',(await eventPromise).data==='still-live'&&safeBuffer.byteLength===2);
    const move=new MessageChannel();let oldReceived=false;move.port2.onmessage=()=>{oldReceived=true;};
    move.port1.postMessage('queued-before-transfer');
    const moved=structuredClone({p:move.port2},{transfer:[move.port2]}).p;
    throws('repeat-transfer',()=>structuredClone(move.port2,{transfer:[move.port2]}),'DataCloneError');
    await wait();t('moved-queue-disabled',!oldReceived);eventPromise=once(moved);
    t('moved-queue-delivered',(await eventPromise).data==='queued-before-transfer');
    move.port2.close();eventPromise=once(moved);move.port1.postMessage('new-owner');t('old-close-isolated',(await eventPromise).data==='new-owner');
    const carry=new MessageChannel();eventPromise=once(c.port2);c.port1.postMessage({port:carry.port2},[carry.port2]);
    const carried=await eventPromise;t('ports-data-identity',carried.ports.length===1&&carried.ports[0]===carried.data.port);
    eventPromise=once(carried.ports[0]);carry.port1.postMessage(42);t('transferred-channel-live',(await eventPromise).data===42);
    const unused=new MessageChannel();eventPromise=once(c.port2);c.port1.postMessage('no-reference',[unused.port2]);
    t('unreferenced-transfer-ports',(await eventPromise).ports.length===1);
    const closed=new MessageChannel();closed.port1.close();
    throws('closed-uncloneable',()=>structuredClone(closed.port1,{transfer:[closed.port1]}),'DataCloneError');
    throws('closed-validates-clone',()=>closed.port1.postMessage(()=>{}),'DataCloneError');
    let dropped=false;closed.port2.onmessage=()=>{dropped=true;};closed.port1.postMessage('discard');await wait();t('close-disentangles',!dropped);
    const setNull=new MessageChannel();setNull.port2.onmessage=null;let nullStarted=false;
    setNull.port2.addEventListener('message',()=>{nullStarted=true;});setNull.port1.postMessage(1);await wait();t('null-handler-starts',nullStarted);
    let reads=0;const e=new MessageEvent('m',{get data(){reads++;return 5;},ports:[c.port1]});
    t('event-read-once',reads===1&&e.data===5&&!e.isTrusted&&Object.isFrozen(e.ports));
    e.initMessageEvent('new',true,true,9,'origin','id',c.port1,[c.port2]);
    t('event-reinit',e.type==='new'&&e.data===9&&e.source===c.port1&&e.ports[0]===c.port2&&e.bubbles);
    throws('event-brand',()=>Object.getOwnPropertyDescriptor(MessageEvent.prototype,'data').get.call({}),'TypeError');
    throws('event-invalid-port',()=>new MessageEvent('m',{ports:[{}]}),'TypeError');
    throws('event-clone',()=>structuredClone(e),'DataCloneError');
    const windowMessages=[];const windowListener=e=>windowMessages.push(e);addEventListener('message',windowListener);
    postMessage('default');postMessage('explicit',location.origin);postMessage('wild','*');postMessage('wrong','https://not-fixture.invalid');
    t('window-async',windowMessages.length===0);await wait();
    t('window-origin-filter',windowMessages.length===3&&windowMessages.map(e=>e.data).join(',')==='default,explicit,wild');
    t('window-event-source',windowMessages.every(e=>e.origin===location.origin&&e.source===window&&e.isTrusted));
    throws('invalid-target',()=>postMessage('bad','not a URL'),'SyntaxError');
    throws('three-argument-undefined',()=>postMessage('bad',undefined,[]),'SyntaxError');
    throws('three-argument-object',()=>postMessage('bad',{},[]),'SyntaxError');
    throws('window-bad-clone',()=>postMessage(()=>{},'*'),'DataCloneError');
    removeEventListener('message',windowListener);
    const nullIterator=new ArrayBuffer(1);eventPromise=once(c.port2);
    c.port1.postMessage(nullIterator,{[Symbol.iterator]:null,transfer:[nullIterator]});
    t('null-iterator-dictionary',(await eventPromise).data.byteLength===1&&nullIterator.byteLength===0);
    const getterOrder=[];
    new MessageEvent('order',Object.fromEntries(['data','lastEventId','origin','ports','source'].map(k=>[k,undefined])));
    const dictionary={};for(const k of ['data','lastEventId','origin','ports','source'])Object.defineProperty(dictionary,k,{get(){getterOrder.push(k);return undefined;}});
    new MessageEvent('order',dictionary);t('dictionary-order',getterOrder.join(',')==='data,lastEventId,origin,ports,source');
    const poison=new MessageChannel();const nativeClone=structuredClone,nativeURL=URL;
    const nativeMessageEvent=MessageEvent,nativeSetTimeout=setTimeout,nativePromise=Promise;
    let poisonEvent;poison.port2.onmessage=e=>{poisonEvent=e;};
    try{
        globalThis.structuredClone=()=>{throw Error('public clone used');};globalThis.URL=()=>{throw Error('public URL used');};
        globalThis.MessageEvent=()=>{throw Error('public event used');};globalThis.setTimeout=()=>{throw Error('public timer used');};
        globalThis.Promise=()=>{throw Error('public Promise used');};poison.port1.postMessage({ok:true});
    }finally{Object.assign(globalThis,{structuredClone:nativeClone,URL:nativeURL,MessageEvent:nativeMessageEvent,setTimeout:nativeSetTimeout,Promise:nativePromise});}
    await wait();t('private-builtins',poisonEvent&&poisonEvent.data.ok);
    const many=new MessageChannel();let n=0;many.port2.onmessage=()=>{n++;};
    for(let i=0;i<200;i++)many.port1.postMessage(i);
    for(let i=0;i<100&&n<200;i++)await wait();t('independent-of-timer-limit',n===200);
    for(const channel of [c,safe,move,carry,unused,closed,setNull,poison,many]){channel.port1.close();channel.port2.close();}
    moved.close();carried.ports[0].close();return count;
}
