globalThis.runObserverCases=async function(){
    let count=0;const ok=(v,n)=>{count++;check('observer-'+n,v);if(!v)throw Error(n);};
    const wait=()=>new Promise(r=>setTimeout(r,40));
    const until=async fn=>{for(let i=0;i<40 && !fn();i++)await wait();ok(fn(),'delivery');};
    const root=document.createElement('div');root.style.cssText='position:absolute;left:0;top:0;width:100px;height:100px;overflow:hidden';
    const box=document.createElement('div');box.style.cssText='position:absolute;left:10px;top:10px;width:20px;height:30px;padding:3px;border:2px solid';
    root.appendChild(box);document.body.appendChild(root);
    let resizes=[],ios=[],receiver;
    const ro=new ResizeObserver(function(es,o){resizes.push(...es);receiver=this;ok(o===ro,'resize-argument');});
    ro.observe(box);ok(resizes.length===0,'resize-not-synchronous');
    await until(()=>resizes.length>0);
    let e=resizes.at(-1);
    ok(receiver===ro && e instanceof ResizeObserverEntry && e.target===box,'resize-identity');
    ok(e.contentRect instanceof DOMRectReadOnly && e.contentRect.width===20 && e.contentRect.height===30,'content-box');
    ok(e.contentRect.x===3 && e.contentRect.y===3,'content-origin');
    ok(e.borderBoxSize[0].inlineSize===30 && e.borderBoxSize[0].blockSize===40,'border-box');
    ok(e.contentBoxSize[0] instanceof ResizeObserverSize && e.contentBoxSize[0].inlineSize===20,'size-interface');
    ok(e.devicePixelContentBoxSize[0].inlineSize===20,'device-pixels');
    const old=resizes.length;await wait();ok(resizes.length===old,'unchanged-no-notification');
    box.style.width='40px';await until(()=>resizes.length>old);ok(resizes.at(-1).contentRect.width===40,'size-change');
    box.style.display='none';await until(()=>resizes.at(-1).contentRect.width===0);ok(resizes.at(-1).contentRect.height===0,'hidden-zero');
    box.style.display='block';await until(()=>resizes.at(-1).contentRect.width===40);
    ro.disconnect();const stopped=resizes.length;box.style.width='20px';await wait();ok(resizes.length===stopped,'resize-disconnect');
    const io=new IntersectionObserver(function(es,o){ios.push(...es);receiver=this;ok(o===io,'intersection-argument');},{root,threshold:[0,.5,1]});
    io.observe(box);ok(ios.length===0,'intersection-not-synchronous');await until(()=>ios.length>0);
    e=ios.at(-1);ok(e instanceof IntersectionObserverEntry && e.target===box && receiver===io,'intersection-identity');
    ok(e.isIntersecting && e.intersectionRatio===1 && e.boundingClientRect.width===30,'fully-inside');
    ok(e.rootBounds.width===100 && e.rootBounds.height===100,'root-bounds');
    box.style.left='85px';await until(()=>ios.at(-1).intersectionRatio===.5);
    ok(ios.at(-1).isIntersecting && ios.at(-1).intersectionRect.width===15,'partly-clipped');
    box.style.left='101px';await until(()=>!ios.at(-1).isIntersecting);ok(ios.at(-1).intersectionRatio===0,'outside-not-visible');
    box.style.left='100px';await until(()=>ios.at(-1).isIntersecting);ok(ios.at(-1).intersectionRatio===0,'edge-adjacent');
    root.removeChild(box);await until(()=>!ios.at(-1).isIntersecting);ok(ios.at(-1).boundingClientRect.width===0,'detached');
    io.disconnect();ok(io.takeRecords().length===0,'take-records');
    ok(io.root===root && io.rootMargin==='0px 0px 0px 0px' && io.thresholds.join(',')==='0,0.5,1','options');
    const margin=new IntersectionObserver(()=>{},{rootMargin:'10% 2px'});
    ok(margin.rootMargin==='10% 2px 10% 2px','margin-expansion');margin.disconnect();
    let thrown=false;try{new IntersectionObserver(()=>{},{threshold:2});}catch(e){thrown=e instanceof RangeError;}ok(thrown,'threshold-range');
    thrown=false;try{new IntersectionObserver(()=>{},{rootMargin:'1em'});}catch(e){thrown=e.name==='SyntaxError';}ok(thrown,'margin-syntax');
    thrown=false;try{ro.observe(document);}catch(e){thrown=e instanceof TypeError;}ok(thrown,'target-brand');
    thrown=false;try{ro.observe(box,{box:'wrong'});}catch(e){thrown=e instanceof TypeError;}ok(thrown,'box-enum');
    root.remove();return count;
};
