/* Native web_live geometry contracts; no DOM or geometry implementation shim. */
function runSVGGeometryCases(){
    let checks=0;
    const check=(name,value)=>{checks++;console.log((value?'OK ':'FAIL ')+name);};
    const near=(name,a,b,epsilon=.003)=>check(name,Number.isFinite(a)&&Math.abs(a-b)<=epsilon);
    const illegal=(name,fn)=>{let error;try{fn();}catch(e){error=e;}check(name,error instanceof TypeError);};
    const NS='http://www.w3.org/2000/svg',make=name=>document.createElementNS(NS,name);
    const svg=document.querySelector('#geometry-root'),g=svg.querySelector('g'),path=g.querySelector('path');
    check('svg-root-graphics-prototype',svg instanceof SVGSVGElement&&svg instanceof SVGGraphicsElement);
    check('svg-group-graphics-prototype',Object.getPrototypeOf(g)===SVGGraphicsElement.prototype&&g instanceof SVGElement);
    check('svg-path-geometry-prototype',Object.getPrototypeOf(path)===SVGPathElement.prototype&&path instanceof SVGGeometryElement&&path instanceof SVGGraphicsElement);
    for(const C of [SVGElement,SVGSVGElement,SVGGraphicsElement,SVGGeometryElement,SVGPathElement,SVGAnimatedRect])illegal('svg-illegal-'+C.name,()=>new C());
    const animated=svg.viewBox,base=animated.baseVal,anim=animated.animVal;
    check('svg-viewBox-animated-brand',animated instanceof SVGAnimatedRect&&Object.prototype.toString.call(animated)==='[object SVGAnimatedRect]');
    check('svg-viewBox-SameObject',svg.viewBox===animated&&animated.baseVal===base&&animated.animVal===anim);
    check('svg-viewBox-rect-types',base instanceof DOMRect&&anim instanceof DOMRectReadOnly&&!(anim instanceof DOMRect));
    check('svg-viewBox-initial-values',base.x===0&&base.y===0&&base.width===100&&base.height===100);
    svg.setAttribute('viewBox','1e1, -2e1, 80, 40');check('svg-viewBox-exponent-live',base.x===10&&base.y===-20&&base.width===80&&base.height===40&&anim.height===40);
    base.x=12;check('svg-viewBox-base-write',svg.getAttribute('viewBox')==='12 -20 80 40'&&anim.x===12);
    check('svg-viewBox-derived-edges',base.left===12&&base.right===92&&base.top===-20&&base.bottom===20);
    let readonly;try{Function('r','"use strict"; r.width=999')(anim);}catch(e){readonly=e;}check('svg-viewBox-anim-readonly',readonly instanceof TypeError&&anim.width===80);
    svg.removeAttribute('viewBox');check('svg-viewBox-remove-live-zero',base.x===0&&base.y===0&&base.width===0&&base.height===0);
    for(const bad of ['0 0 -1 10','0 0 10','0 0 NaN 1','0 0 1 1 trailing']){svg.setAttribute('viewBox',bad);check('svg-viewBox-invalid-'+bad,base.width===0&&base.height===0);}
    svg.setAttribute('viewBox','0 0 0 10');check('svg-viewBox-zero-valid',base.width===0&&base.height===10);
    svg.setAttribute('viewBox','0 0 100 100');
    const viewGetter=Object.getOwnPropertyDescriptor(SVGSVGElement.prototype,'viewBox').get;
    for(const wrong of [{},document.createElement('svg'),g])illegal('svg-viewBox-receiver',()=>viewGetter.call(wrong));
    illegal('svg-animated-rect-receiver',()=>Object.getOwnPropertyDescriptor(SVGAnimatedRect.prototype,'baseVal').get.call({}));
    illegal('svg-rect-value-receiver',()=>Object.getOwnPropertyDescriptor(DOMRect.prototype,'width').get.call({}));
    const cloned=svg.cloneNode(true);check('svg-viewBox-clone-independent',cloned.viewBox!==animated&&cloned.viewBox.baseVal.width===100);
    cloned.viewBox.baseVal.width=50;check('svg-viewBox-clone-mutation',base.width===100&&cloned.viewBox.baseVal.width===50);
    const other=document.implementation.createHTMLDocument();other.adoptNode(cloned);check('svg-viewBox-adopt-live',cloned.ownerDocument===other&&cloned.viewBox.baseVal.width===50);
    const rootMatrix=svg.getScreenCTM();check('svg-screen-ctm-native-matrix',rootMatrix instanceof DOMMatrix&&rootMatrix.is2D);
    near('svg-viewBox-meet-scale',rootMatrix.a,1);near('svg-viewBox-meet-y-scale',rootMatrix.d,1);
    // Absolute positioned SVG at (10,20), 200x100, square viewBox: xMid adds 50.
    near('svg-screen-ctm-layout-x',rootMatrix.e,60);near('svg-screen-ctm-layout-y',rootMatrix.f,20);
    near('svg-outer-getCTM-document-x',svg.getCTM().e,60);near('svg-outer-getCTM-document-y',svg.getCTM().f,20);
    near('svg-path-getCTM-viewport-x',path.getCTM().e,60);near('svg-path-getCTM-viewport-y',path.getCTM().f,20);
    near('svg-path-screen-only-css-x',path.getScreenCTM().e-path.getCTM().e,10);
    near('svg-path-screen-only-css-y',path.getScreenCTM().f-path.getCTM().f,20);
    const relative=rootMatrix.inverse().multiply(path.getScreenCTM()),sample=new DOMPoint(3,4).matrixTransform(relative);
    near('svg-transform-order-x',sample.x,16);near('svg-transform-order-y',sample.y,32);
    const before=path.getScreenCTM();g.setAttribute('transform','matrix(1 0 0 1 7 9)');const after=rootMatrix.inverse().multiply(path.getScreenCTM());
    near('svg-transform-mutation-x',after.e,7);near('svg-transform-mutation-y',after.f,9);check('svg-ctm-detached-snapshot',before!==path.getScreenCTM()&&before.e!==path.getScreenCTM().e);
    g.setAttribute('transform','translate(10 20) scale(2 3)');
    svg.setAttribute('preserveAspectRatio','none');near('svg-viewBox-none-x-scale',svg.getCTM().a,2);near('svg-viewBox-none-y-scale',svg.getCTM().d,1);
    svg.setAttribute('preserveAspectRatio','xMaxYMax slice');near('svg-viewBox-slice-scale',svg.getScreenCTM().d,2);near('svg-viewBox-slice-y',svg.getScreenCTM().f,-80);
    svg.removeAttribute('preserveAspectRatio');
    const nested=make('svg'),nestedPath=make('path');nested.setAttribute('x','25');nested.setAttribute('y','10');nested.setAttribute('width','50');nested.setAttribute('height','40');nested.setAttribute('viewBox','0 0 10 10');
    nested.setAttribute('preserveAspectRatio','none');nested.appendChild(nestedPath);svg.appendChild(nested);
    const nr=rootMatrix.inverse().multiply(nestedPath.getScreenCTM());near('svg-nested-viewport-x',nr.e,25);near('svg-nested-viewport-y',nr.f,10);near('svg-nested-viewport-scale',nr.a,5);
    near('svg-nearest-getCTM-not-screen',nestedPath.getCTM().e,25);
    near('svg-nested-root-getCTM-ancestor',nested.getCTM().e,75);
    check('svg-unconnected-ctm-null',make('path').getScreenCTM()===null&&make('svg').getCTM()===null);
    illegal('svg-ctm-receiver',()=>SVGGraphicsElement.prototype.getScreenCTM.call({}));
    illegal('svg-ctm-real-nongraphics-receiver',()=>SVGGraphicsElement.prototype.getCTM.call(make('linearGradient')));
    const local=make('path');local.setAttribute('d','M0 0 L3 4 M100 100 L106 108');
    near('svg-compound-move-not-length',local.getTotalLength(),15);
    near('svg-compound-before-move-x',local.getPointAtLength(5).x,3);
    near('svg-compound-after-move-x',local.getPointAtLength(10).x,103);near('svg-compound-after-move-y',local.getPointAtLength(10).y,104);
    near('svg-distance-clamp-low',local.getPointAtLength(-20).x,0);near('svg-distance-clamp-high',local.getPointAtLength(100).y,108);
    const point=local.getPointAtLength(10);point.x=999;near('svg-point-detached-snapshot',local.getPointAtLength(10).x,103);
    local.setAttribute('d','M0 0 L3 0 L3 4 Z');near('svg-closepath-length',local.getTotalLength(),12);near('svg-closepath-end',local.getPointAtLength(12).y,0);
    local.setAttribute('d','M10 0 A10 10 0 0 1 0 10');near('svg-arc-length',local.getTotalLength(),Math.PI*5,.01);
    near('svg-arc-middle-x',local.getPointAtLength(local.getTotalLength()/2).x,Math.SQRT1_2*10,.02);
    near('svg-arc-middle-y',local.getPointAtLength(local.getTotalLength()/2).y,Math.SQRT1_2*10,.02);
    local.setAttribute('d','m1 2 h3 v4 h-3 z');near('svg-relative-hvz-length',local.getTotalLength(),14);
    local.setAttribute('d','M0 0 Q5 10 10 0 T20 0');check('svg-quadratic-smooth-length',local.getTotalLength()>20&&local.getTotalLength()<35);near('svg-quadratic-end',local.getPointAtLength(999).x,20);
    local.setAttribute('d','M0 0 C0 10 10 10 10 0 S20 -10 20 0');check('svg-cubic-smooth-length',local.getTotalLength()>30&&local.getTotalLength()<45);near('svg-cubic-end',local.getPointAtLength(999).x,20);
    local.setAttribute('d','M7 8');near('svg-move-only-length',local.getTotalLength(),0);near('svg-move-only-point',local.getPointAtLength(0).x,7);
    local.setAttribute('d','');near('svg-empty-length',local.getTotalLength(),0);
    illegal('svg-path-method-receiver',()=>SVGGeometryElement.prototype.getTotalLength.call(svg));
    illegal('svg-distance-required',()=>local.getPointAtLength());illegal('svg-distance-infinite',()=>local.getPointAtLength(Infinity));illegal('svg-distance-NaN',()=>local.getPointAtLength(NaN));
    const cached=make('path');cached.setAttribute('d','M0 0 L100 0');console.log('SVG-CACHE-BEGIN');
    let sum=0;for(let i=0;i<1024;i++)sum+=cached.getPointAtLength((i+.5)/1024*cached.getTotalLength()).x;
    near('svg-1024-samples-index-values',sum,51200,.1);console.log('SVG-CACHE-CHECK 1');
    cached.setAttribute('d','M0 0 L200 0');near('svg-path-mutation-refresh',cached.getTotalLength(),200);
    for(let i=0;i<1024;i++)cached.getPointAtLength(i/1024*200);console.log('SVG-CACHE-CHECK 2');
    cached.setAttribute('pathLength','1');cached.setAttribute('transform','scale(10)');near('svg-pathLength-transform-not-local-length',cached.getTotalLength(),200);
    for(let i=0;i<1024;i++)cached.getPointAtLength(i);console.log('SVG-CACHE-CHECK 2');
    const geometryCopy=cached.cloneNode();near('svg-path-clone-local-length',geometryCopy.getTotalLength(),200);other.adoptNode(cached);near('svg-path-adopt-local-length',cached.getTotalLength(),200);
    cached.setAttribute('d','M0 0 L20 0');near('svg-path-adopt-cache-refresh',cached.getTotalLength(),20);
    const savedGet=local.getAttribute;local.getAttribute=()=>{throw new Error('public getter used');};local.setAttribute('d','M0 0 L5 0');near('svg-private-attribute-read',local.getTotalLength(),5);local.getAttribute=savedGet;
    const m=new DOMMatrix([2,0,0,3,10,20]),p=new DOMPoint(3,4),q=p.matrixTransform(m);
    check('dom-point-defaults',new DOMPoint().z===0&&new DOMPoint().w===1);near('dom-point-matrix-x',q.x,16);near('dom-point-matrix-y',q.y,32);
    near('dom-matrix-inverse-roundtrip',q.matrixTransform(m.inverse()).x,3);
    const product=new DOMMatrix().translate(10,20).scale(2,3);near('dom-matrix-post-multiply-order',product.transformPoint(p).y,32);
    const pre=new DOMMatrix().translate(10,20);pre.preMultiplySelf(new DOMMatrix().scale(2,3));near('dom-matrix-pre-multiply-order',pre.e,20);
    check('dom-matrix-singular-NaN',Number.isNaN(new DOMMatrix([0,0,0,0,0,0]).inverse().a));
    const spatial=new DOMMatrix([1,0,0,0,0,1,0,0,0,0,2,0,3,4,5,1]),sp=spatial.transformPoint({x:1,y:2,z:3,w:2});
    check('dom-matrix-3d-data',spatial.is2D===false&&sp.x===7&&sp.y===10&&sp.z===16&&sp.w===2);
    near('dom-matrix-3d-inverse',sp.matrixTransform(spatial.inverse()).z,3);
    illegal('dom-matrix-alias-conflict',()=>DOMMatrix.fromMatrix({a:2,m11:3}));illegal('dom-matrix-illegal-2d',()=>DOMMatrix.fromMatrix({m13:1,is2D:true}));
    illegal('dom-point-matrix-brand',()=>DOMPointReadOnly.prototype.matrixTransform.call({},m));illegal('dom-matrix-inverse-brand',()=>DOMMatrixReadOnly.prototype.inverse.call({}));
    check('dom-matrix-readonly-factory',DOMMatrixReadOnly.fromMatrix(m) instanceof DOMMatrixReadOnly&&!(DOMMatrixReadOnly.fromMatrix(m) instanceof DOMMatrix));
    check('svg-factory-point-matrix',svg.createSVGPoint() instanceof DOMPoint&&svg.createSVGMatrix() instanceof DOMMatrix);
    illegal('svg-factory-root-brand',()=>SVGSVGElement.prototype.createSVGMatrix.call(g));
    console.log('SVG-GEOMETRY-JS-CHECKS '+checks);return checks;
}
