static unsigned checks,failures;
static void check(bool ok,const char *name){checks++;if(!ok){failures++;printf("FAIL %s\n",name);}}
int main(void){
    bool wired=false;for(size_t i=0;i<sizeof simple_pcs/sizeof *simple_pcs;i++)if(!strcmp(simple_pcs[i].name,"active"))wired=simple_pcs[i].pc==PC_ACTIVE;
    check(wired,"active selector no longer always false");
    web_doc top={.live=true},child={.live=true},grand={.live=true},other={.live=true};
    node_t root={.type=N_DOC,.owner=&top},cr={.type=N_DOC,.owner=&child},gr={.type=N_DOC,.owner=&grand},orr={.type=N_DOC,.owner=&other};
    top.root=&root;child.root=&cr;grand.root=&gr;other.root=&orr;doc=&top;
    node_t parent={.type=N_ELEM,.tag=T_div,.parent=&root,.owner=&top},button={.type=N_ELEM,.tag=T_button,.parent=&parent,.owner=&top},sibling={.type=N_ELEM,.tag=T_div,.parent=&parent,.owner=&top};
    top.hover_target=&sibling;web_active_press(&top,&button);
    check(css_active(&button)&&css_active(&parent)&&!css_active(&sibling),"press matches true target and flat ancestors only");
    check(top.active_leaf==&top&&top.active_target==&button,"native state records owning target");
    check(top.hover_target==&sibling,"active state is independent of hover");
    check(top.dirty&&top.need_style&&!top.resources_dirty,"press invalidates styles without resource loading");
    struct gui_event e={.type=EV_MOUSE_MOVE,.buttons=1,.x=-100,.y=-100};native_active_event(&e);
    check(css_active(&button),"drag outside retains press until physical release");
    e.type=EV_MOUSE_UP;e.buttons=1;native_active_event(&e);
    check(css_active(&button),"secondary-button release does not cancel primary");
    e.buttons=0;native_active_event(&e);
    check(!top.active_leaf&&!top.active_target&&!css_active(&button),"outside captured release clears before callbacks");
    top.dirty=top.need_style=false;web_active_release(&top);
    check(!top.dirty&&!top.need_style,"redundant release has no restyle side effects");
    web_active_press(&top,&button);e.type=EV_UNFOCUS;native_active_event(&e);
    check(!top.active_leaf&&!css_active(&parent),"native focus/capture loss cancels press");
    web_active_press(&top,&button);e.type=EV_CLOSE;native_active_event(&e);
    check(!top.active_leaf&&!css_active(&button),"native Close cancels without author dispatch");
    web_active_press(&top,&button);e.type=EV_MOUSE_MOVE;e.buttons=0;native_active_event(&e);
    check(!top.active_leaf,"pointer button state loss cancels missed release");
    web_active_press(&top,&button);doc_active_cancel(&other);
    check(css_active(&button),"unrelated document cancellation preserves press");
    web_active_release(&top);button.parent=NULL;web_active_press(&top,&button);
    check(!top.active_leaf,"detached initial target rejected");button.parent=&parent;
    inert_node=&button;web_active_press(&top,&button);check(!top.active_leaf,"modal inert target cannot become active");inert_node=NULL;
    node_t foreign={.type=N_ELEM,.owner=&other,.parent=&orr};web_active_press(&top,&foreign);
    check(!top.active_leaf&&!other.active_target,"unrelated target cannot forge press");
    node_t frame_node={.type=N_ELEM,.tag=T_iframe,.parent=&root,.owner=&top};
    node_t inner_frame={.type=N_ELEM,.tag=T_iframe,.parent=&cr,.owner=&child};
    node_t inside={.type=N_ELEM,.tag=T_button,.parent=&gr,.owner=&grand};
    struct web_frame f={.owner=&top,.element=&frame_node,.document=&child},g={.owner=&child,.element=&inner_frame,.document=&grand};
    top.frames=&f;child.frames=&g;child.frame_parent=&top;child.frame_element=&frame_node;grand.frame_parent=&child;grand.frame_element=&inner_frame;
    web_active_press(&top,&inside);
    check(top.active_leaf==&grand&&child.active_target==&inner_frame&&top.active_target==&frame_node,"nested press publishes real embedding chain");
    check(css_active(&inside)&&css_active(&inner_frame)&&css_active(&frame_node)&&!css_active(&button),"each realm matches its own frame ancestry");
    check(grand.need_style&&child.need_style&&top.need_style,"nested press invalidates each context's native style");
    doc_active_cancel(&other);check(css_active(&inside),"retiring non-pressed context leaves nested press intact");
    doc_active_cancel(&child);
    check(!top.active_leaf&&!top.active_target&&!child.active_target&&!grand.active_target,"ancestor context cancellation clears entire press chain");
    web_active_press(&top,&inside);web_frame_retire(&g);
    check(!top.active_leaf&&!css_active(&frame_node)&&!css_active(&inside),"real frame retirement cancels outer and descendant active selectors");
    check(g.retired==&grand&&!g.document&&!grand.live,"retirement retains arena while disabling old context");
    grand.live=true;g.document=&grand;g.retired=NULL;
    g.detached=true;web_active_press(&top,&inside);check(!top.active_leaf,"detached browsing generation rejected");g.detached=false;
    g.document=NULL;web_active_press(&top,&inside);check(!top.active_leaf,"replaced child generation rejected");g.document=&grand;
    inner_frame.parent=NULL;web_active_press(&top,&inside);check(!top.active_leaf,"disconnected embedding ancestor rejected");inner_frame.parent=&cr;
    inert_node=&frame_node;web_active_press(&top,&inside);check(!top.active_leaf,"outer modal inert embedding rejects child press");inert_node=NULL;
    web_active_press(&top,&inside);inside.parent=NULL;
    check(!css_active(&inside)&&!css_active(&frame_node),"retained detached child target cannot keep parent active");inside.parent=&gr;web_active_release(&top);
    web_active_press(&top,&inside);web_frames_detach_tree(&top,&frame_node);
    check(!top.active_leaf&&!child.active_target&&!grand.active_target,"native frame subtree removal cancels press before detach");
    f.document=&child;f.retired=NULL;f.detached=false;child.live=true;
    web_active_press(&top,&button);web_frames_detach_tree(&top,&parent);
    check(!top.active_leaf&&!top.active_target,"ordinary subtree detach hook cancels native press");
    button.parent=NULL;button.parent=&parent;check(!css_active(&button),"reinsertion does not revive cancelled native press");
    node_t host={.type=N_ELEM,.tag=T_div,.owner=&top,.parent=&root},shadow={.type=N_FRAGMENT,.owner=&top,.shadow_host=&host,.shadow_manual=true},slot={.type=N_ELEM,.tag=T_slot,.owner=&top,.parent=&shadow};
    host.shadow_root=&shadow;node_t light={.type=N_ELEM,.tag=T_button,.owner=&top,.parent=&host,.manual_slot=&slot};
    web_active_press(&top,&light);
    check(css_active(&light)&&css_active(&slot)&&css_active(&host),"slotted press follows actual flat-tree slot and host");
    web_frames_detach_tree(&top,&host);check(!top.active_leaf&&!css_active(&slot),"shadow host removal cancels slotted press");
    node_t shadow_button={.type=N_ELEM,.tag=T_button,.owner=&top,.parent=&shadow};
    web_active_press(&top,&shadow_button);check(css_active(&shadow_button)&&css_active(&host),"shadow descendant press reaches host without exposed property");
    web_frames_detach_tree(&top,&host);check(!top.active_leaf,"shadow-inclusive native removal clears descendant press");
    web_active_press(&top,&button);doc_active_cancel(&top);
    check(!top.active_leaf&&!top.active_target,"root destruction cancels before native arenas are freed");
    top.live=false;web_active_press(&top,&button);check(!top.active_leaf,"inactive top cannot publish press");
    printf("native-active18: %u checks, %u failures\n",checks,failures);return failures!=0;
}
