const throws=(callback,name)=>{try{callback()}catch(e){return e.name===name}return false;};
const style=fixtureDom('style'),link=fixtureDom('link'),cross=fixtureDom('cross'),shadow=fixtureDom('shadow');
const list=document.styleSheets;
check(list===document.styleSheets&&list instanceof StyleSheetList,'SameObject branded native StyleSheetList');
check(list.length===5,'native document list includes two inline and completed HTTP/data links only');
check(list[0]===style.sheet&&list.item(1)===link.sheet,'native tree order and owner sheet identity');
check(list.item(999)===null&&list[999]===undefined,'item missing is null and indexed missing is undefined');
check(throws(()=>list.item(),'TypeError')&&throws(()=>new StyleSheetList(),'TypeError'),'StyleSheetList required index and illegal constructor');
check(throws(()=>Object.getOwnPropertyDescriptor(Document.prototype,'styleSheets').get.call(style),'TypeError'),'document getter rejects an Element receiver');
check(throws(()=>Object.getOwnPropertyDescriptor(StyleSheetList.prototype,'length').get.call({}),'TypeError'),'list getter rejects arbitrary objects');
check([...list].length===list.length&&new Set([...list].map(e=>e.href)).has(link.sheet.href),'actual failing GitHub iterable href Set pattern reads native sheets');
check(link.sheet.href==='https://parent.test/a.css'&&style.sheet.href===null,'external committed href and inline null href');
check(link.sheet.ownerNode===link&&style.sheet.ownerNode===style,'real owner nodes');
check(link.sheet.cssRules[0].selectorText==='.a'&&link.sheet.rules===link.sheet.cssRules,'loaded link exposes native parser rule list and legacy alias');
check(cross.sheet.href==='https://cross.test/x.css'&&cross.sheet.ownerNode===cross,'cross-origin sheet is enumerable without leaking rules');
check(throws(()=>cross.sheet.cssRules,'SecurityError')&&throws(()=>cross.sheet.rules,'SecurityError'),'cross-origin read APIs reject with SecurityError');
check(throws(()=>cross.sheet.insertRule('.leak{}'),'SecurityError')&&throws(()=>cross.sheet.deleteRule(0),'SecurityError'),'cross-origin mutation APIs reject with SecurityError');
check(shadow.styleSheets.length===1&&shadow.styleSheets[0].cssRules[0].selectorText==='.shadow','shadow sheet list is separately scoped');
check([...list].every(e=>e.ownerNode!==shadow.styleSheets[0].ownerNode),'document excludes shadow sheets and template content');
check(fixtureDom('data').sheet.href.startsWith('data:')&&fixtureDom('data').sheet.cssRules[0].selectorText==='.data','data stylesheet uses actual decoded native CSS');
const linked=link.sheet;linked.disabled=true;
// Corrected after the first run: link.disabled remains the HTML attribute
// reflection, not a sheet.disabled alias. These corrected two are NOT rerun.
check(linked.disabled&&!fixtureDom('applies')&&list.length===5,'disabled sheet remains associated but stops native cascade application');
linked.disabled=false;
check(!linked.disabled&&fixtureDom('applies')&&link.sheet===linked,'CSSOM re-enable uses its native flag without replacing its sheet');
linked.insertRule('.added {height:2px}',1);
check(linked.cssRules.length===2&&linked.cssRules[1].selectorText==='.added','linked CSSOM mutation changes real native rule AST');
const original=style.sheet;fixtureDom('detach');
check(list.length===4&&list[0]===link.sheet&&original.ownerNode===null,'retained list tracks native removal and old owner disassociation');
fixtureDom('reinsert');
check(list.length===5&&list[0]===style.sheet&&style.sheet!==original,'native reinsert creates a new associated sheet identity');
const oldLink=link.sheet;fixtureDom('href');
check(link.sheet!==oldLink&&link.sheet.href==='https://parent.test/b.css'&&oldLink.href==='https://parent.test/a.css'&&oldLink.ownerNode===null,'href change invalidates only new association and preserves old sheet href');
fixtureDom('text');
check(list[0].cssRules[0].selectorText==='.changed','style text replacement is reflected in native list');
const before=list.length;fixtureDom('pendingLoad');
check(list.length===before+1&&list[2].href==='https://parent.test/pending.css','native resource completion invalidates a retained live list without a DOM revision');
check(Reflect.set(list,'0',link.sheet)===false&&Reflect.defineProperty(list,'0',{value:link.sheet})===false,'read-only indexed list cannot be replaced by author data');
check(throws(()=>new CSSStyleSheet(),'NotSupportedError'),'constructed/adopted support is not fabricated');
globalThis.savedSheet=list[0];
