/* 新26だけ：別QuickJS runtime、製品のnative prepare/publish/child送信。 */
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>
#include <string.h>
#include <quickjs.h>
#include "../user/libc/web/js_worker.h"
#include "../user/include/js_worker_wire.h"
#include "../user/libc/web/js_worker_transfer.h"
#include "../build/goal-20261009/worker-broker26-new-once/native-extract.h"
static JSRuntime *parent_rt,*child_rt;static JSContext *parent_ctx,*child_ctx;
static JSValue parent_hooks,child_hooks;static web_workers parent_workers;static struct child child_record;static struct worker child_worker;
static unsigned assertions,failures;static bool deny_publication;
static void check(const char *name,int ok){assertions++;printf("%s %s\n",ok?"PASS":"FAIL",name);if(!ok)failures++;}
static int exception(JSContext*c,const char *phase){if(!JS_HasException(c))return 0;JSValue e=JS_GetException(c);const char*s=JS_ToCString(c,e);printf("FIXTURE_EXCEPTION %s %s\n",phase,s?s:"unknown");JS_FreeCString(c,s);JS_FreeValue(c,e);failures++;return 1;}
static JSValue native_check(JSContext*c,JSValueConst t,int n,JSValueConst*a){(void)t;const char*s=n?JS_ToCString(c,a[0]):NULL;check(s?s:"missing-name",n>1&&JS_ToBool(c,a[1])>0);JS_FreeCString(c,s);return JS_UNDEFINED;}
static JSValue native_class(JSContext*c,JSValueConst t,int n,JSValueConst*a){(void)t;return JS_NewUint32(c,n?JS_GetClassID(a[0]):0);}
static JSValue native_frame(JSContext*c,JSValueConst t,int n,JSValueConst*a){(void)t;const char*op=n?JS_ToCString(c,a[0]):NULL;JSValue r=JS_UNDEFINED;if(op&&!strcmp(op,"transferGeneration"))r=JS_NewUint32(c,71);else if(op&&!strcmp(op,"transferCommit"))r=worker_transfer_commit(c,a[1],!child_record.stopped);else if(op&&!strcmp(op,"messageBrand"))r=JS_TRUE;JS_FreeCString(c,op);return r;}
static JSValue native_parent_worker(JSContext*c,JSValueConst t,int n,JSValueConst*a){(void)t;uint32_t op,id,port=0,creator=0;if(n<2||JS_ToUint32(c,&op,a[0])||JS_ToUint32(c,&id,a[1]))return JS_EXCEPTION;
 if(op==4)return JS_NewUint32(c,++child_record.parent_port);
 if(n<4)return JS_ThrowTypeError(c,"private broker arguments");if(op!=3&&(JS_ToUint32(c,&port,a[4])||JS_ToUint32(c,&creator,a[5])))return JS_EXCEPTION;
 if(deny_publication)return JS_ThrowOutOfMemory(c);
 web_worker_publication*p=web_worker_prepare(&parent_workers,id,op==3?NJW_MESSAGE:op==6?NJW_PORT_MESSAGE:NJW_PORT_CLOSE,port,op==3?NJW_WITH_PORTS:creator,a[2]);if(!p)return JS_EXCEPTION;
 JSValue r=worker_transfer_commit(c,a[3],!child_record.stopped);if(JS_IsException(r))web_worker_abort(p);else web_worker_publish(p);return r;}
static JSValue native_commit(JSContext*c,JSValueConst t,int n,JSValueConst*a){(void)t;return n?worker_transfer_commit(c,a[0],!child_worker.closed):JS_EXCEPTION;}
static JSValue native_now(JSContext*c,JSValueConst t,int n,JSValueConst*a){(void)t;(void)n;(void)a;return JS_NewInt32(c,100);}
static JSValue native_ignore(JSContext*c,JSValueConst t,int n,JSValueConst*a){(void)c;(void)t;(void)n;(void)a;return JS_UNDEFINED;}
static JSValue native_wire_check(JSContext*c,JSValueConst t,int n,JSValueConst*a){(void)t;const char*s=n?JS_ToCString(c,a[0]):NULL;if(s&&!strcmp(s,"broker-preflight-native-reject"))deny_publication=true;else if(s&&!strcmp(s,"broker-preflight-native-allow"))deny_publication=false;else{JS_FreeCString(c,s);return JS_ThrowTypeError(c,"unknown fixture fault");}JS_FreeCString(c,s);return JS_UNDEFINED;}
static JSValue evaluate(JSContext*c,const char*path){FILE*f=fopen(path,"rb");if(!f)return JS_EXCEPTION;fseek(f,0,SEEK_END);long n=ftell(f);rewind(f);char*p=malloc(n+1);fread(p,1,n,f);fclose(f);p[n]=0;JSValue r=JS_Eval(c,p,n,path,JS_EVAL_TYPE_GLOBAL);free(p);return r;}
static bool jobs(JSRuntime*r){while(JS_IsJobPending(r)){JSContext*c;int n=JS_ExecutePendingJob(r,&c);if(n<0){exception(c,"job");return false;}if(!n)break;}return true;}
static JSValue call(JSContext*c,JSValue hooks,const char*name,int argc,JSValueConst*a){JSValue fn=JS_GetPropertyStr(c,hooks,name),r=JS_Call(c,fn,JS_UNDEFINED,argc,a);JS_FreeValue(c,fn);return r;}
static bool pump_parent(void){while(child_record.tx){struct packet*p=child_record.tx;child_record.tx=p->next;if(!child_record.tx)child_record.tail=NULL;parent_workers.queued-=sizeof p->h+p->h.bytes;JSValue v=JS_ReadObject(child_ctx,p->data,p->h.bytes,JS_READ_OBJ_REFERENCE);if(JS_IsException(v)){free(p->data);free(p);exception(child_ctx,"child-wire-read");return false;}JSValue a[]={v,JS_NewUint32(child_ctx,p->h.op),JS_NewUint32(child_ctx,p->h.request),JS_NewUint32(child_ctx,p->h.kind)};JSValue r=call(child_ctx,child_hooks,"receive",4,a);for(int i=0;i<4;i++)JS_FreeValue(child_ctx,a[i]);JS_FreeValue(child_ctx,r);free(p->data);free(p);if(exception(child_ctx,"child-wire")||!jobs(child_rt))return false;}return true;}
static bool pump_child(void){while(child_worker.output){struct outgoing*p=child_worker.output;child_worker.output=p->next;if(!child_worker.output)child_worker.last_output=NULL;child_worker.output_bytes-=sizeof p->h+p->h.bytes;JSValue v=JS_ReadObject(parent_ctx,p->data,p->h.bytes,JS_READ_OBJ_REFERENCE);if(JS_IsException(v)){js_free(child_ctx,p->data);free(p);exception(parent_ctx,"parent-wire-read");return false;}
 if(p->h.op==NJW_MESSAGE&&p->h.kind==NJW_WITH_PORTS){struct broker_pair*ports=NULL;if(!broker_metadata(parent_ctx,&child_record,v,1,&ports)){JS_FreeValue(parent_ctx,v);return false;}while(ports){struct broker_pair*x=ports;ports=x->next;x->next=child_record.ports;child_record.ports=x;}}
 else if(p->h.op==NJW_PORT_MESSAGE||p->h.op==NJW_PORT_CLOSE){struct broker_pair*x=broker_find(&child_record,p->h.request,p->h.kind);if(!x||x->closed){check("broker-unexpected-native-route",false);return false;}if(p->h.op==NJW_PORT_CLOSE)x->closed=true;}
 JSValue a[]={v,JS_NewUint32(parent_ctx,p->h.op),JS_NewUint32(parent_ctx,p->h.request),JS_NewUint32(parent_ctx,p->h.kind)};JSValue r=call(parent_ctx,parent_hooks,"receive",4,a);for(int i=0;i<4;i++)JS_FreeValue(parent_ctx,a[i]);JS_FreeValue(parent_ctx,r);js_free(child_ctx,p->data);free(p);if(exception(parent_ctx,"parent-wire")||!jobs(parent_rt))return false;}return true;}
static bool tick(JSContext*c,JSRuntime*r,JSValue hooks){JSValue a=JS_NewInt32(c,100),v=call(c,hooks,"tick",1,&a);JS_FreeValue(c,v);JS_FreeValue(c,a);return !exception(c,"task")&&jobs(r);}
int main(void){setvbuf(stdout,NULL,_IONBF,0);parent_rt=JS_NewRuntime();child_rt=JS_NewRuntime();parent_ctx=JS_NewContext(parent_rt);child_ctx=JS_NewContext(child_rt);JS_SetMaxStackSize(parent_rt,512*1024);JS_SetMaxStackSize(child_rt,512*1024);parent_workers.ctx=parent_ctx;parent_workers.generation=71;parent_workers.children=&child_record;child_record.id=1;child_record.in=child_record.out=-1;child_worker.ctx=child_ctx;child_worker.rt=child_rt;child_worker.generation=71;JS_SetContextOpaque(child_ctx,&child_worker);
 JSContext*contexts[]={parent_ctx,child_ctx};for(unsigned i=0;i<2;i++){JSContext*c=contexts[i];JSValue g=JS_GetGlobalObject(c),h=JS_NewObject(c);const JSCFunctionListEntry funcs[]={JS_CFUNC_DEF("classID",1,native_class),JS_CFUNC_DEF("transferCommit",1,native_commit),JS_CFUNC_DEF("frame",2,native_frame),JS_CFUNC_DEF("worker",6,native_parent_worker),JS_CFUNC_DEF("portSend",5,native_port_send),JS_CFUNC_DEF("now",0,native_now),JS_CFUNC_DEF("send",3,native_ignore),JS_CFUNC_DEF("detach",1,native_ignore),JS_CFUNC_DEF("close",0,native_ignore)};JS_SetPropertyFunctionList(c,h,funcs,sizeof funcs/sizeof*funcs);if(i)JS_DeleteProperty(c,h,JS_NewAtom(c,"frame"),0);JS_SetPropertyStr(c,g,i?"__workerHost":"__parentHost",h);JS_SetPropertyStr(c,g,"__check",JS_NewCFunction(c,native_check,"check",2));JS_SetPropertyStr(c,g,"__fault",JS_NewCFunction(c,native_wire_check,"fault",1));JS_FreeValue(c,g);}
 check("new-broker-wire-is-24-byte-generation-preserved",sizeof(struct njw_header)==24&&parent_workers.generation==child_worker.generation);
 parent_hooks=evaluate(parent_ctx,"build/goal-20261009/worker-broker26-new-once/parent-bootstrap.js");child_hooks=evaluate(child_ctx,"build/goal-20261009/worker-broker26-new-once/child-bootstrap.js");if(exception(parent_ctx,"parent-bootstrap")||exception(child_ctx,"child-bootstrap"))goto out;
 for(unsigned phase=0;phase<8;phase++){char path[128];snprintf(path,sizeof path,"build/goal-20261009/worker-broker26-new-once/phase%u.js",phase);JSContext*c=(phase==1||phase==3||phase==5)?child_ctx:parent_ctx;JSValue v=evaluate(c,path);JS_FreeValue(c,v);if(exception(c,"phase")||!jobs(c==parent_ctx?parent_rt:child_rt)||!pump_parent()||!pump_child())break;for(unsigned j=0;j<4;j++)if(!tick(parent_ctx,parent_rt,parent_hooks)||!tick(child_ctx,child_rt,child_hooks)||!pump_parent()||!pump_child())goto out;}
out:while(child_record.tx){struct packet*p=child_record.tx;child_record.tx=p->next;free(p->data);free(p);}while(child_worker.output){struct outgoing*p=child_worker.output;child_worker.output=p->next;js_free(child_ctx,p->data);free(p);}broker_free(child_record.ports);JS_FreeValue(parent_ctx,parent_hooks);JS_FreeValue(child_ctx,child_hooks);JS_FreeContext(parent_ctx);JS_FreeContext(child_ctx);JS_FreeRuntime(parent_rt);JS_FreeRuntime(child_rt);printf("RESULT %u assertions %u failures\n",assertions,failures);return failures?1:0;}
