#!/usr/bin/env python3
"""Copy the pinned, unmodified Lexbor subset from a local upstream checkout."""
import hashlib
import json
from pathlib import Path
import shutil
import subprocess
import sys

REVISION = "f4cbbcd91359a0ec9499e3ce7e263de629482d61"
MODULES = ("core", "dom", "ns", "tag", "html", "css", "selectors", "encoding")


def output(args):
    return subprocess.check_output(args, encoding="utf-8").strip()


def main():
    if len(sys.argv) != 2:
        raise SystemExit("usage: python ports/lexbor/vendor.py LOCAL_LEXBOR_CHECKOUT")
    source = Path(sys.argv[1]).resolve()
    destination = Path(__file__).resolve().parents[2] / "third_party" / "lexbor"
    if output(["git", "-C", str(source), "rev-parse", "HEAD"]) != REVISION:
        raise SystemExit("upstream revision differs from the pinned revision")
    if output(["git", "-C", str(source), "status", "--porcelain"]):
        raise SystemExit("upstream checkout must be unmodified")

    entries = ["LICENSE", "NOTICE", "README.md"]
    for module in MODULES:
        directory = source / "source" / "lexbor" / module
        paths = output(["rg", "--files", str(directory), "-g", "*.c", "-g", "*.h",
                        "-g", "config.cmake"]).splitlines()
        entries.extend(Path(path).relative_to(source).as_posix() for path in paths)

    manifest = []
    for entry in sorted(entries):
        src, dst = source / entry, destination / entry
        data = src.read_bytes()
        if dst.exists() and dst.read_bytes() != data:
            raise SystemExit(f"refusing to replace locally modified file: {entry}")
        dst.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(src, dst)
        manifest.append({"path": entry, "sha256": hashlib.sha256(data).hexdigest()})
    record = {"upstream": "https://github.com/lexbor/lexbor", "revision": REVISION,
              "version": "3.1.0", "modules": MODULES, "files": manifest}
    (destination / "UPSTREAM.json").write_text(
        json.dumps(record, ensure_ascii=False, indent=2) + "\n", encoding="utf-8", newline="\n")
    # Host MSYS2 does not bundle ripgrep. Build from the pinned discovery list;
    # only vendoring needs git/rg, not ordinary OS compilation or sysroot staging.
    sources = [f"third_party/lexbor/{entry}" for entry in sorted(entries) if entry.endswith(".c")]
    headers = [f"third_party/lexbor/{entry}" for entry in sorted(entries) if entry.endswith(".h")]
    lines = ["# Generated by ports/lexbor/vendor.py; upstream " + REVISION,
             "LXB_VENDOR_C :="]
    lines.extend("LXB_VENDOR_C += " + path for path in sources)
    lines.append("LXB_HEADERS :=")
    lines.extend("LXB_HEADERS += " + path for path in headers)
    (destination / "sources.mk").write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    (destination / "headers.list").write_text("\n".join(headers) + "\n", encoding="utf-8", newline="\n")
    print(f"vendored {len(manifest)} unmodified files from {REVISION}")


if __name__ == "__main__":
    main()
