#!/usr/bin/env python3
"""Convert a BDF bitmap font into a C header usable by both kernel and userland.

Glyph slots 0-255 hold Latin-1, except the control ranges (1-31, 127, 128-159),
which are filled with handy Unicode symbols (box drawing, blocks, arrows, a moon...).
A Unicode -> slot table is emitted too so text renderers can decode UTF-8.
"""
import sys

EXTRA = {
    1: 0x263A, 2: 0x263B, 3: 0x2665, 4: 0x2666, 5: 0x2663, 6: 0x2660, 7: 0x2022,
    8: 0x25D8, 9: 0x25CB, 10: 0x25D9, 11: 0x2642, 12: 0x2640, 13: 0x266A, 14: 0x266B,
    15: 0x263C, 16: 0x25BA, 17: 0x25C4, 18: 0x2195, 19: 0x203C, 20: 0x00B6, 21: 0x00A7,
    22: 0x25AC, 23: 0x21A8, 24: 0x2191, 25: 0x2193, 26: 0x2192, 27: 0x2190, 28: 0x221F,
    29: 0x2194, 30: 0x25B2, 31: 0x25BC, 127: 0x2302,
    0x80: 0x2588, 0x81: 0x2593, 0x82: 0x2592, 0x83: 0x2591, 0x84: 0x2500, 0x85: 0x2502,
    0x86: 0x250C, 0x87: 0x2510, 0x88: 0x2514, 0x89: 0x2518, 0x8A: 0x251C, 0x8B: 0x2524,
    0x8C: 0x252C, 0x8D: 0x2534, 0x8E: 0x253C, 0x8F: 0x2550, 0x90: 0x2551, 0x91: 0x2554,
    0x92: 0x2557, 0x93: 0x255A, 0x94: 0x255D, 0x95: 0x2580, 0x96: 0x2584, 0x97: 0x25CF,
    0x98: 0x263E, 0x99: 0x2605, 0x9A: 0x2606, 0x9B: 0x2713, 0x9C: 0x2717, 0x9D: 0x258C,
    0x9E: 0x2590, 0x9F: 0x2026,
}


def parse_bdf(path):
    glyphs = {}
    fbb = None
    ascent = None
    with open(path, encoding="latin-1") as f:
        lines = f.read().splitlines()
    i = 0
    while i < len(lines):
        ln = lines[i]
        if ln.startswith("FONTBOUNDINGBOX"):
            fbb = list(map(int, ln.split()[1:]))
        elif ln.startswith("FONT_ASCENT"):
            ascent = int(ln.split()[1])
        elif ln.startswith("STARTCHAR"):
            enc = None
            bbx = None
            i += 1
            while not lines[i].startswith("BITMAP"):
                p = lines[i].split()
                if p[0] == "ENCODING":
                    enc = int(p[1])
                elif p[0] == "BBX":
                    bbx = list(map(int, p[1:]))
                i += 1
            i += 1
            rows = []
            while not lines[i].startswith("ENDCHAR"):
                rows.append(int(lines[i], 16))
                i += 1
            glyphs[enc] = (bbx, rows)
        i += 1
    return fbb, ascent, glyphs


def render(fbb, ascent, glyph):
    W, H = fbb[0], fbb[1]
    bbx, rows = glyph
    gw, gh, gx, gy = bbx
    nbytes = (gw + 7) // 8
    cell = [[0] * W for _ in range(H)]
    top = ascent - (gy + gh)
    for r, bits in enumerate(rows):
        y = top + r
        if not 0 <= y < H:
            continue
        for c in range(gw):
            if bits & (1 << (nbytes * 8 - 1 - c)):
                x = gx + c
                if 0 <= x < W:
                    cell[y][x] = 1
    out = []
    rb = (W + 7) // 8
    for y in range(H):
        v = 0
        for x in range(W):
            if cell[y][x]:
                v |= 1 << (rb * 8 - 1 - x)
        out.extend(v.to_bytes(rb, "big"))
    return out


def main():
    src, name, out, full = sys.argv[1], sys.argv[2], sys.argv[3], sys.argv[4] == "full"
    fbb, ascent, glyphs = parse_bdf(src)
    if ascent is None:
        ascent = fbb[1] + fbb[3]
    W, H = fbb[0], fbb[1]
    slots = []
    umap = []
    for s in range(256):
        cp = EXTRA.get(s, s) if full else s
        if not full and not (32 <= s < 127):
            cp = None
        if cp is not None and cp in glyphs:
            slots.append(render(fbb, ascent, glyphs[cp]))
            if cp != s:
                umap.append((cp, s))
        elif s in glyphs and (32 <= s < 127):
            slots.append(render(fbb, ascent, glyphs[s]))
        else:
            slots.append([0] * (H * ((W + 7) // 8)))
    with open(out, "w") as f:
        f.write("/* Generated by scripts/bdf2c.py from %s. Spleen font: BSD-2-Clause, (c) Frederic Cambus. */\n" % src.replace("\\", "/").split("/")[-1])
        f.write("#pragma once\n#include <stdint.h>\n")
        f.write("#define %s_W %d\n#define %s_H %d\n" % (name.upper(), W, name.upper(), H))
        f.write("static const uint8_t %s_data[256][%d] = {\n" % (name, len(slots[0])))
        for s, g in enumerate(slots):
            f.write("  {" + ",".join("0x%02x" % b for b in g) + "},\n")
        f.write("};\n")
        if full:
            umap.sort()
            f.write("static const uint16_t %s_umap[][2] = {\n" % name)
            for cp, s in umap:
                f.write("  {0x%04x, 0x%02x},\n" % (cp, s))
            f.write("};\n#define %s_UMAP_COUNT %d\n" % (name.upper(), len(umap)))


main()
