"""Turn a PEM CA bundle into BearSSL trust anchors (C source).

usage: python mkroots.py ca-bundle.crt out.c

Only the subject name and public key of each root are needed; RSA and the NIST P-256/384/521
curves are supported (that covers every root in the Mozilla bundle that matters)."""
import base64
import re
import sys

EC_CURVES = {"1.2.840.10045.3.1.7": 23, "1.3.132.0.34": 24, "1.3.132.0.35": 25}


def tlv(d, o):
    """parse one DER element at offset o -> (tag, header_len, content_start, end)"""
    tag = d[o]
    ln = d[o + 1]
    p = o + 2
    if ln & 0x80:
        n = ln & 0x7F
        ln = int.from_bytes(d[p:p + n], "big")
        p += n
    return tag, p, p + ln


def children(d, start, end):
    out = []
    o = start
    while o < end:
        tag, cs, ce = tlv(d, o)
        out.append((tag, o, cs, ce))
        o = ce
    return out


def oid(b):
    vals = [b[0] // 40, b[0] % 40]
    v = 0
    for x in b[1:]:
        v = (v << 7) | (x & 0x7F)
        if not x & 0x80:
            vals.append(v)
            v = 0
    return ".".join(map(str, vals))


def strip0(b):
    while len(b) > 1 and b[0] == 0:
        b = b[1:]
    return b


def parse(der):
    _, cs, ce = tlv(der, 0)
    tbs = children(der, cs, ce)[0]
    f = children(der, tbs[2], tbs[3])
    if f[0][0] == 0xA0:
        f = f[1:]
    # serial, sigalg, issuer, validity, subject, spki
    subj = f[4]
    dn = der[subj[1]:subj[3]]
    spki = children(der, f[5][2], f[5][3])
    alg = children(der, spki[0][2], spki[0][3])
    alg_oid = oid(der[alg[0][2]:alg[0][3]])
    bits = der[spki[1][2] + 1:spki[1][3]]  # skip the unused-bits byte
    if alg_oid == "1.2.840.113549.1.1.1":
        _, kcs, kce = tlv(bits, 0)
        n, e = children(bits, kcs, kce)[:2]
        return dn, ("rsa", strip0(bits[n[2]:n[3]]), strip0(bits[e[2]:e[3]]))
    if alg_oid == "1.2.840.10045.2.1" and len(alg) > 1:
        curve = EC_CURVES.get(oid(der[alg[1][2]:alg[1][3]]))
        if curve:
            return dn, ("ec", curve, bits)
    return None


def carr(name, b):
    body = ",".join("0x%02x" % x for x in b)
    return "static const unsigned char %s[] = {%s};\n" % (name, body)


def main():
    pem = open(sys.argv[1], encoding="ascii", errors="replace").read()
    blocks = re.findall(r"-----BEGIN CERTIFICATE-----(.*?)-----END CERTIFICATE-----", pem, re.S)
    out = ['/* generated by scripts/mkroots.py from the Mozilla CA bundle - do not edit */\n',
           '#include "bearssl.h"\n\n']
    entries = []
    for blk in blocks:
        try:
            r = parse(base64.b64decode("".join(blk.split())))
        except Exception:
            r = None
        if not r:
            continue
        i = len(entries)
        dn, key = r
        out.append(carr("DN%d" % i, dn))
        if key[0] == "rsa":
            out.append(carr("N%d" % i, key[1]))
            out.append(carr("E%d" % i, key[2]))
            k = "{BR_KEYTYPE_RSA, {.rsa = {(unsigned char *)N%d, sizeof N%d, (unsigned char *)E%d, sizeof E%d}}}" % (
                i, i, i, i)
        else:
            out.append(carr("Q%d" % i, key[2]))
            k = "{BR_KEYTYPE_EC, {.ec = {%d, (unsigned char *)Q%d, sizeof Q%d}}}" % (key[1], i, i)
        entries.append("    {{(unsigned char *)DN%d, sizeof DN%d}, BR_X509_TA_CA, %s}" % (i, i, k))
    out.append("\nconst br_x509_trust_anchor tls_trust_anchors[] = {\n%s\n};\n" % ",\n".join(entries))
    out.append("const size_t tls_trust_anchors_num = %d;\n" % len(entries))
    open(sys.argv[2], "w").write("".join(out))
    print("  mkroots: %d of %d roots" % (len(entries), len(blocks)))


main()
